WIP in-game InputDisplay
stblr/mkw-sp pull request #121
Opened 2022-02-05 21:45 UTC by riidefi

NOTE: The game appears to OOM with both speedometer and input display loaded.

Screenshot: 
![image](https://user-images.githubusercontent.com/34194588/152660024-eede30e0-0fec-412d-a0c2-49337df2d310.png)

2022-02-07 20:40 UTC, riidefi commented
Fully functional now, with brakedrifting support.

Footage: https://www.youtube.com/watch?v=t8t-7oNTlVU

2022-02-08 04:25 UTC, riidefi commented
Added license setting

2022-02-08 11:18 UTC, stblr requested changes
This looks great overall. On top of the code-related comments, there are a few visual issues:
- The position is wrong in 4:3.
- The input display overlaps with the position tracker in VS.
- The scale of some buttons seems to be off.
- The brake drifting button is weirdly positioned.
- The shape of the stick circle is only valid for GCN controllers.

2022-02-08 11:18 UTC, stblr commented on payload/game/ui/Layout.h
> +}
The RTTI check is missing and a `Layout` type should be defined.

2022-02-08 11:18 UTC, stblr commented on payload/game/ui/page/RacePage.S
> +    add r3, r3, r30 // Increase the control count by one CtrlRaceInputDisplay per local player
Split-screen should be handled in some way (not necessarily here).

2022-02-08 11:18 UTC, stblr commented on payload/game/system/SaveManager.h
> +    u32 settingRaceInputDisplay : 3;
Reserving space for more presets is a good idea, but since not all options are valid yet a check should be added in the `SpSaveLicense_sanitize` function (and the initialization in `SaveManager_createSpLicense` is missing too).

2022-02-08 19:13 UTC, riidefi commented
I've moved the InputDisplay up to avoid intersecting the position tracker, although I don't think it looks the best.

Remaining issues:
1. The brake drifting button is weirdly positioned.
2. Different circle stick for nunchuck and wheel.

2022-02-08 19:57 UTC, stblr approved these changes

2022-02-08 19:58 UTC, merged