[WIP] GC keyboard driver
stblr/mkw-sp pull request #253
Opened 2022-04-02 19:20 UTC by riidefi

2022-04-02 22:53 UTC, stblr requested changes
Otherwise LGTM if conflicts are resolved.

2022-04-02 22:53 UTC, stblr commented on payload/sp/SIKeyboard.c
> +    return 3;
Unused

2022-04-02 23:41 UTC, riidefi commented on payload/sp/SIKeyboard.c
> +    return 3;
The initial `& 0xff`?

2022-04-03 08:37 UTC, stblr approved these changes

2022-04-03 08:38 UTC, merged