XOR the return address of functions with the value of the global stack canary
stblr/mkw-sp pull request #270
Opened 2022-04-12 20:45 UTC by StarMKWii

2022-04-12 21:03 UTC, stblr requested changes

2022-04-12 21:03 UTC, stblr commented on payload/sp/Stack.c
> +static inline bool Stack_IsFunctionEpilogue(const u32* start_address, const u32* end_address)
There is no need for `inline` in .c files with modern compilers.

2022-04-12 21:13 UTC, riidefi commented
We will need to update StackTrace.c to account for encrypted pointers.

2022-04-12 21:30 UTC, StarMKWii commented on payload/sp/Stack.c
> +            goto label_check_next_function;
Indeed. However, I believe that we would use `stw` instead of `stw + 1`, no ?

2022-04-12 21:50 UTC, stblr commented on payload/sp/Stack.c
> +            goto label_check_next_function;
No, because the first instruction will be checked (unless I'm missing something).

2022-04-13 01:35 UTC, riidefi commented on payload/sp/Stack.c
> +            goto label_check_next_function;
At request of Star:

they're functionally equivalent:
1. the check is lwz in [stw, mtlr] and lwz >= stw
2. the second is effectively lwz in [stw + 1, infinity]
3. since we are checking both expressions we can simply union the two ranges `[stw, mtlr]` and `[stw + 1, infinity]`
4. the union is  `[stw + 1, mtlr]`
5. therefore, the check can be rewritten `lwz in [stw + 1, mtlr]`
but if you don't want to disregard the case when `stw == lwz`, then remove the check

2022-04-13 01:41 UTC, riidefi commented on payload/sp/Stack.c
> +            goto label_check_next_function;
Oh no, we are falsely assuming an inclusive lower bound. The check is effectively a no-op, and you want to preserve the case when `lwz == stw + `.

2022-04-13 01:42 UTC, riidefi commented on payload/sp/Stack.c
> +            goto label_check_next_function;
So just delete the two lines.

2022-04-13 02:00 UTC, riidefi commented on payload/sp/Stack.c
> +            goto label_check_next_function;
FindNextFunction accepts `[X, Y)` and provides `[X, Y)` to its callback
FindLastFunction accepts `(X, Y)` and provides `(X, Y]` to its callback

This is really strange.

2022-04-13 11:58 UTC, stblr commented on payload/sp/Stack.c
> +            goto label_check_next_function;
FindNextFunction and/or FindLastFunction should be changed to be more consistent.

2022-04-13 22:15 UTC, StarMKWii commented on payload/sp/Stack.c
> +            goto label_check_next_function;
Addressed in commit [3a7ed06](https://github.com/stblr/mkw-sp/pull/270/commits/3a7ed06df50ba80f9b6430c0020d49ec6eeaf5be).

2022-04-13 22:15 UTC, StarMKWii commented on payload/sp/Stack.c
> +        ICInvalidateRange(lwz, sizeof(lwz));
Addressed in commit [9d8a9ae](https://github.com/stblr/mkw-sp/pull/270/commits/9d8a9aebf74785fb3648d0ed0fa35dd423519341).

2022-04-13 22:15 UTC, StarMKWii commented on payload/sp/Stack.c
> +static inline bool Stack_IsFunctionEpilogue(const u32* start_address, const u32* end_address)
Addressed in commit [0a7d648](https://github.com/stblr/mkw-sp/pull/270/commits/0a7d6481293d7e19748fa29a5a31cbe27482f6c2).

2022-04-13 22:39 UTC, stblr commented on payload/sp/Stack.c
> +        u32* lwz = Stack_FindLastFunction(stw, mtlr, Stack_IsLinkRegisterRestoreInstruction, 1);
This can be `stw + 1` now.

2022-04-14 04:05 UTC, StarMKWii commented on payload/sp/Stack.c
> +        u32* lwz = Stack_FindLastFunction(stw, mtlr, Stack_IsLinkRegisterRestoreInstruction, 1);
Addressed in commit [6c21ede](https://github.com/stblr/mkw-sp/pull/270/commits/6c21edec9ec4fbeb3ca1bfa91c1364388f6c5091).

2022-04-14 08:24 UTC, stblr approved these changes

2022-04-14 08:24 UTC, stblr commented
Resolved conflicts and applied.

2022-04-14 08:24 UTC, closed without merging

2022-04-14 21:50 UTC, StarMKWii commented
> We will need to update StackTrace.c to account for encrypted pointers.

Addressed in commit [dac37eb](https://github.com/stblr/mkw-sp/pull/272/commits/dac37eb1ff196012a3aa63a5e72542f19f9b7d84).