Implement FriendRoomPage for easier modification
stblr/mkw-sp pull request #385
Opened 2022-08-16 08:07 UTC by vabold

This will aim to give more infrastructure for future room development, and will solve `Leave a room` in #382.

2022-08-16 08:18 UTC, stblr requested changes

2022-08-16 08:18 UTC, stblr commented on payload/game/ui/FriendRoomPage.cc
> +#include "FriendRoomPage.hh"
One blank line after this include

2022-08-16 08:18 UTC, stblr commented on payload/game/ui/FriendRoomPage.cc
> +void FriendRoomPage::onInit() {
Please follow the same order as the other custom pages.

2022-08-16 08:18 UTC, stblr commented on payload/game/ui/FriendRoomPage.cc
> +    m_messageButton.setSelectHandler(&m_onButtonSelect, false);
Wrong button

2022-08-16 08:18 UTC, stblr commented on payload/game/ui/FriendRoomPage.cc
> +    // I think this function's name is createGlobalContext, so I'll use that
Certainly not

2022-08-16 08:18 UTC, stblr commented on payload/game/ui/FriendRoomPage.cc
> +    Page *messageSelectPage = SectionManager::Instance()->currentSection()->page(PageId::FriendRoomMessageSelectPage)->downcast<Page>();
Use the template version

2022-08-16 08:18 UTC, stblr commented on payload/game/ui/FriendRoomPage.cc
> +}
An array would be cleaner, or one handler per button.

2022-08-16 08:18 UTC, stblr commented on payload/game/ui/FriendRoomPage.cc
> +    yesNoPage->setWindowMessage((m_roomRole == RoomRole::Host) + 4019, nullptr);
We have our own ids.

2022-08-16 08:18 UTC, stblr commented on payload/game/ui/FriendRoomPage.hh
> +#include "game/ui/MenuInputManager.hh"
Ordering

2022-08-16 08:18 UTC, stblr commented on payload/game/ui/FriendRoomPage.hh
> +    void onRefocus() override;
One blank line after this

2022-08-16 08:18 UTC, stblr commented on payload/game/ui/FriendRoomPage.hh
> +    // TODO: are message IDs hex?
They are decimal

2022-08-16 08:18 UTC, stblr commented on payload/game/ui/FriendRoomPage.hh
> +    PushButton m_messageButton;
Maybe rename to `m_commentButton`, since message already refers to different things (BMGs, data sent over the network).

2022-08-16 08:18 UTC, stblr commented on payload/game/ui/FriendRoomPage.hh
> +    s32 m_messageId = 2001;
Please only add fields that are currently needed

2022-08-16 08:18 UTC, stblr commented on payload/game/ui/FriendRoomPage.hh
> +    bool m_somethingRegister;
Same

2022-08-16 08:18 UTC, stblr commented on payload/game/ui/PageId.hh
> +    FriendRoomMessageSelectPage = 0x9e, // possibly something more generic?
I don't think it's generic(?)

2022-08-19 01:43 UTC, vabold commented on payload/game/ui/FriendRoomPage.cc
> +#include "FriendRoomPage.hh"
Resolved in https://github.com/vabold/mkw-sp/commit/ebc49348937f2857d39e0ff3c8cc0c5f1449d9d8.

2022-08-19 01:44 UTC, vabold commented on payload/game/ui/FriendRoomPage.cc
> +void FriendRoomPage::onInit() {
Resolved in https://github.com/vabold/mkw-sp/commit/ebc49348937f2857d39e0ff3c8cc0c5f1449d9d8.

2022-08-19 01:44 UTC, vabold commented on payload/game/ui/FriendRoomPage.cc
> +    // I think this function's name is createGlobalContext, so I'll use that
Resolved in https://github.com/vabold/mkw-sp/commit/ebc49348937f2857d39e0ff3c8cc0c5f1449d9d8.

2022-08-19 01:44 UTC, vabold commented on payload/game/ui/FriendRoomPage.cc
> +    Page *messageSelectPage = SectionManager::Instance()->currentSection()->page(PageId::FriendRoomMessageSelectPage)->downcast<Page>();
Resolved in https://github.com/vabold/mkw-sp/commit/ebc49348937f2857d39e0ff3c8cc0c5f1449d9d8.

2022-08-19 01:44 UTC, vabold commented on payload/game/ui/FriendRoomPage.cc
> +}
Resolved in https://github.com/vabold/mkw-sp/commit/ebc49348937f2857d39e0ff3c8cc0c5f1449d9d8.

2022-08-19 01:44 UTC, vabold commented on payload/game/ui/FriendRoomPage.cc
> +    yesNoPage->setWindowMessage((m_roomRole == RoomRole::Host) + 4019, nullptr);
Resolved in https://github.com/vabold/mkw-sp/commit/ebc49348937f2857d39e0ff3c8cc0c5f1449d9d8.

2022-08-19 01:44 UTC, vabold commented on payload/game/ui/FriendRoomPage.hh
> +#include "game/ui/MenuInputManager.hh"
Resolved in https://github.com/vabold/mkw-sp/commit/ebc49348937f2857d39e0ff3c8cc0c5f1449d9d8.

2022-08-19 01:44 UTC, vabold commented on payload/game/ui/FriendRoomPage.hh
> +    void onRefocus() override;
Resolved in https://github.com/vabold/mkw-sp/commit/ebc49348937f2857d39e0ff3c8cc0c5f1449d9d8.

2022-08-19 01:44 UTC, vabold commented on payload/game/ui/FriendRoomPage.hh
> +    // TODO: are message IDs hex?
Resolved in https://github.com/vabold/mkw-sp/commit/ebc49348937f2857d39e0ff3c8cc0c5f1449d9d8.

2022-08-19 01:44 UTC, vabold commented on payload/game/ui/FriendRoomPage.hh
> +    s32 m_messageId = 2001;
Resolved in https://github.com/vabold/mkw-sp/commit/ebc49348937f2857d39e0ff3c8cc0c5f1449d9d8.

2022-08-19 01:44 UTC, vabold commented on payload/game/ui/FriendRoomPage.hh
> +    bool m_somethingRegister;
Resolved in https://github.com/vabold/mkw-sp/commit/ebc49348937f2857d39e0ff3c8cc0c5f1449d9d8.

2022-08-19 01:47 UTC, vabold commented on payload/game/ui/PageId.hh
> +    FriendRoomMessageSelectPage = 0x9e, // possibly something more generic?
I think it is slightly more generic. The register menu and the comment menu seem to share the same page, at least as far as I can tell.

2022-08-19 08:50 UTC, stblr commented on payload/game/ui/PageId.hh
> +    FriendRoomMessageSelectPage = 0x9e, // possibly something more generic?
I think you mean the close menu (to choose the game mode).

2022-08-19 08:55 UTC, vabold commented on payload/game/ui/PageId.hh
> +    FriendRoomMessageSelectPage = 0x9e, // possibly something more generic?
Yes, that's right, I confused myself for a second.

2022-08-19 08:58 UTC, stblr commented on payload/game/ui/PageId.hh
> +    FriendRoomMessageSelectPage = 0x9e, // possibly something more generic?
I think we should keep `FriendRoomMessageSelect` because the name is used both in the code (control class name) and in the BRCTR file names.

2022-08-19 08:59 UTC, vabold commented on payload/game/ui/PageId.hh
> +    FriendRoomMessageSelectPage = 0x9e, // possibly something more generic?
Agreed.

2022-08-20 10:05 UTC, stblr requested changes

2022-08-20 10:05 UTC, stblr commented on payload/game/ui/FriendRoomPage.cc
> +    }
Move this to `onBackConfirm`?

2022-08-20 10:05 UTC, stblr commented on payload/game/ui/FriendRoomPage.cc
> +    yesNoPage->configureButton(0, 4012, nullptr, Anim::None, nullptr);
Also bind `onBackConfirm` here.

2022-08-20 10:05 UTC, stblr commented on payload/game/ui/FriendRoomPage.cc
> +        }
We shouldn't need these checks here.

2022-08-20 10:05 UTC, stblr commented on payload/game/ui/PageId.hh
> +    FriendRoomMessageSelectPage = 0x9e,
The `Page` suffix can be dropped.

2022-08-20 10:05 UTC, stblr commented on payload/game/ui/UIControl.hh
> +
I don't think we need this.

2022-08-20 10:05 UTC, stblr commented on payload/game/ui/FriendRoomPage.cc
> +// Base function: 0x805d820c
These annotations can be dropped.

2022-08-20 12:56 UTC, vabold commented on payload/game/ui/FriendRoomPage.cc
> +    }
https://github.com/stblr/mkw-sp/pull/385/commits/5f68b835c8707299fa93f62fcba05a59ec92b589

2022-08-20 12:57 UTC, vabold commented on payload/game/ui/FriendRoomPage.cc
> +    yesNoPage->configureButton(0, 4012, nullptr, Anim::None, nullptr);
Resolved in https://github.com/stblr/mkw-sp/pull/385/commits/5f68b835c8707299fa93f62fcba05a59ec92b589.

2022-08-20 12:57 UTC, vabold commented on payload/game/ui/FriendRoomPage.cc
> +        }
Resolved in https://github.com/stblr/mkw-sp/pull/385/commits/5f68b835c8707299fa93f62fcba05a59ec92b589.

2022-08-20 12:57 UTC, vabold commented on payload/game/ui/PageId.hh
> +    FriendRoomMessageSelectPage = 0x9e,
Resolved in https://github.com/stblr/mkw-sp/pull/385/commits/5f68b835c8707299fa93f62fcba05a59ec92b589.

2022-08-20 12:57 UTC, vabold commented on payload/game/ui/UIControl.hh
> +
Resolved in https://github.com/stblr/mkw-sp/pull/385/commits/5f68b835c8707299fa93f62fcba05a59ec92b589.

2022-08-20 12:57 UTC, vabold commented on payload/game/ui/FriendRoomPage.cc
> +// Base function: 0x805d820c
Resolved in https://github.com/stblr/mkw-sp/pull/385/commits/5f68b835c8707299fa93f62fcba05a59ec92b589.

2022-08-20 13:00 UTC, stblr approved these changes
LGTM

2022-08-20 13:01 UTC, merged