Add room closing
stblr/mkw-sp pull request #401
Opened 2022-08-30 18:00 UTC by vabold

Aims to solve `Start a room` and `Choose character/vehicle/drift` in #382.

2022-09-05 23:47 UTC, vabold commented
There are so many problems here that need to be fixed.

TODO: task list

2022-09-10 22:05 UTC, vabold commented
The last step of this PR is to send an initial packet with character/vehicle info to the server. This packet will be reused for changing character/vehicle in between races.

2022-09-11 17:09 UTC, stblr requested changes

2022-09-11 17:09 UTC, stblr commented on payload/game/system/GameScene.hh
> +    static GameScene* get();
Uppercase

2022-09-11 17:09 UTC, stblr commented on payload/game/system/ResourceManager.hh
> +    static ResourceManager *Instance() { return s_instance; }
Static functions at the end

2022-09-11 17:09 UTC, stblr commented on payload/game/ui/FriendMatchingPage.cc
> +    driftSelectPage->setReplacementSection((SectionId)(m_gamemode + 0x60));
`static_cast`

2022-09-11 17:09 UTC, stblr commented on payload/game/ui/MenuServerPage.hh
> +class MenuServerPage : public Page {
Since this is both for the client and the server, maybe rename it to e.g. `RoomVotingPage`.

2022-09-11 17:09 UTC, stblr commented on payload/game/ui/ModelRenderPage.cc
> +    }
Do we need this?

2022-09-11 17:09 UTC, stblr commented on payload/game/ui/ModelRenderPage.cc
> +    HeapCollection_setGroupIdAll(&gameScene->volatileHeapCollection, 0);
We don't need this line since we change the group id again immediately after.

2022-09-11 17:09 UTC, stblr commented on payload/game/ui/ModelRenderPage.cc
> +    HeapCollection_setGroupIdAll(&gameScene->volatileHeapCollection, 0);
As above

2022-09-11 17:09 UTC, stblr commented on payload/game/ui/ModelRenderPage.cc
> +    }
We have a patch in Model.S to always use MEM1. It can now be removed and the condition should be adapted here.

2022-09-11 17:09 UTC, stblr commented on payload/game/ui/ModelRenderPage.hh
> +
Can be dropped

2022-09-11 17:09 UTC, stblr commented on payload/game/ui/model/MenuModelManager.hh
> +    static MenuModelManager *Instance() { return s_instance; }
Static functions at the end

2022-09-11 17:09 UTC, stblr commented on payload/game/ui/MenuServerPage.cc
> +    }
Don't forget the client

2022-09-11 18:32 UTC, vabold commented on payload/game/system/GameScene.hh
> +    static GameScene* get();
I don't use GameScene.hh. I will clean this up in the next commit.

2022-09-11 18:32 UTC, vabold commented on payload/game/system/ResourceManager.hh
> +    static ResourceManager *Instance() { return s_instance; }
Resolved in https://github.com/stblr/mkw-sp/pull/401/commits/98618805a2ce5ff5cec697a8c8e5def957501c39.

2022-09-11 18:33 UTC, vabold commented on payload/game/ui/FriendMatchingPage.cc
> +    driftSelectPage->setReplacementSection((SectionId)(m_gamemode + 0x60));
Resolved in https://github.com/stblr/mkw-sp/pull/401/commits/98618805a2ce5ff5cec697a8c8e5def957501c39.

2022-09-11 18:33 UTC, vabold commented on payload/game/ui/MenuServerPage.hh
> +class MenuServerPage : public Page {
Resolved in https://github.com/stblr/mkw-sp/pull/401/commits/98618805a2ce5ff5cec697a8c8e5def957501c39.

2022-09-11 18:33 UTC, vabold commented on payload/game/ui/ModelRenderPage.cc
> +    }
Resolved in https://github.com/stblr/mkw-sp/pull/401/commits/98618805a2ce5ff5cec697a8c8e5def957501c39.

2022-09-11 18:33 UTC, vabold commented on payload/game/ui/ModelRenderPage.cc
> +    HeapCollection_setGroupIdAll(&gameScene->volatileHeapCollection, 0);
Resolved in https://github.com/stblr/mkw-sp/pull/401/commits/98618805a2ce5ff5cec697a8c8e5def957501c39.

2022-09-11 18:33 UTC, vabold commented on payload/game/ui/ModelRenderPage.cc
> +    HeapCollection_setGroupIdAll(&gameScene->volatileHeapCollection, 0);
Resolved in https://github.com/stblr/mkw-sp/pull/401/commits/98618805a2ce5ff5cec697a8c8e5def957501c39.

2022-09-11 18:33 UTC, vabold commented on payload/game/ui/ModelRenderPage.cc
> +    }
Resolved in https://github.com/stblr/mkw-sp/pull/401/commits/98618805a2ce5ff5cec697a8c8e5def957501c39.

2022-09-11 18:33 UTC, vabold commented on payload/game/ui/ModelRenderPage.hh
> +
Resolved in https://github.com/stblr/mkw-sp/pull/401/commits/98618805a2ce5ff5cec697a8c8e5def957501c39.

2022-09-11 18:33 UTC, vabold commented on payload/game/ui/model/MenuModelManager.hh
> +    static MenuModelManager *Instance() { return s_instance; }
Resolved in https://github.com/stblr/mkw-sp/pull/401/commits/98618805a2ce5ff5cec697a8c8e5def957501c39.

2022-09-11 18:33 UTC, vabold commented on payload/game/ui/MenuServerPage.cc
> +    }
Resolved in https://github.com/stblr/mkw-sp/pull/401/commits/98618805a2ce5ff5cec697a8c8e5def957501c39.

2022-09-11 18:41 UTC, stblr requested changes

2022-09-11 18:41 UTC, stblr commented on symbols.txt
> +0x8081cd3c _ZN2SP10RoomServer23getCharacterWeightClassEj
Duplicate symbols

2022-09-11 18:41 UTC, stblr commented on symbols.txt
> +0x8051bed0 _Z13GameScene_getv
Shouldn't be needed. Maybe a missing `extern "C"`?

2022-09-11 18:41 UTC, stblr commented on payload/sp/cs/RoomServer.hh
> +    static u32 getVehicleWeightClass(u32 vehicleId);
That's certainly not a function of `RoomServer`, maybe this should go somewhere in `Registry.hh`?

2022-09-11 18:41 UTC, stblr commented on payload/sp/cs/RoomServer.cc
> +        // SP_LOG("Client::read: !pb_decode");
Leftover debug prints

2022-09-11 18:41 UTC, stblr commented on payload/sp/cs/RoomServer.cc
> +        return State::Select;
This will only move the current client (so, the host) to the `Select` stage. I would suggest returning `Main` instead, and checking `m_server.m_state` at the very top of `RoomServer::Client::calcMain` and returning `Select` immediately if it's `Select`.

2022-09-11 18:41 UTC, stblr commented on payload/game/ui/FriendMatchingPage.cc
> +#include "game/ui/page/DriftSelectPage.hh"
Subfolder includes should go after direct ones.

2022-09-11 18:41 UTC, stblr commented on payload/game/ui/Section.cc
> +#include "game/ui/page/DriftSelectPage.hh"
Same as above.

2022-09-11 18:41 UTC, stblr commented on payload/game/ui/page/DriftSelectPage.hh
> +    REPLACE void onButtonFront(PushButton *button);
One blank line after

2022-09-11 18:41 UTC, stblr commented on payload/sp/cs/RoomServer.hh
> +        s32 vehicleId;
`u32`

2022-09-11 18:41 UTC, stblr commented on payload/sp/cs/RoomServer.hh
> +    bool onReceiveProperties(u32 playerId, s32 characterId, s32 vehicleId, bool driftIsAuto);
`u32`

2022-09-11 18:41 UTC, stblr commented on payload/game/ui/page/DriftSelectPage.cc
> +}
Wouldn't it be simpler to send all the data at once with the track vote, unless we need it for something else before?

2022-09-12 06:39 UTC, vabold commented on symbols.txt
> +0x8081cd3c _ZN2SP10RoomServer23getCharacterWeightClassEj
Resolved in https://github.com/stblr/mkw-sp/pull/401/commits/d9206b7315a4259150cd8d98bc4e72216ef1998d.

2022-09-12 06:40 UTC, vabold commented on symbols.txt
> +0x8051bed0 _Z13GameScene_getv
Resolved in https://github.com/stblr/mkw-sp/pull/401/commits/d9206b7315a4259150cd8d98bc4e72216ef1998d.

2022-09-12 06:40 UTC, vabold commented on payload/sp/cs/RoomServer.hh
> +    static u32 getVehicleWeightClass(u32 vehicleId);
Resolved in https://github.com/stblr/mkw-sp/pull/401/commits/d9206b7315a4259150cd8d98bc4e72216ef1998d.

2022-09-12 06:40 UTC, vabold commented on payload/sp/cs/RoomServer.cc
> +        // SP_LOG("Client::read: !pb_decode");
Resolved in https://github.com/stblr/mkw-sp/pull/401/commits/d9206b7315a4259150cd8d98bc4e72216ef1998d.

2022-09-12 06:40 UTC, vabold commented on payload/sp/cs/RoomServer.cc
> +        return State::Select;
Resolved in https://github.com/stblr/mkw-sp/pull/401/commits/d9206b7315a4259150cd8d98bc4e72216ef1998d.

2022-09-12 06:40 UTC, vabold commented on payload/game/ui/FriendMatchingPage.cc
> +#include "game/ui/page/DriftSelectPage.hh"
Resolved in https://github.com/stblr/mkw-sp/pull/401/commits/d9206b7315a4259150cd8d98bc4e72216ef1998d.

2022-09-12 06:40 UTC, vabold commented on payload/game/ui/Section.cc
> +#include "game/ui/page/DriftSelectPage.hh"
Resolved in https://github.com/stblr/mkw-sp/pull/401/commits/d9206b7315a4259150cd8d98bc4e72216ef1998d.

2022-09-12 06:40 UTC, vabold commented on payload/game/ui/page/DriftSelectPage.hh
> +    REPLACE void onButtonFront(PushButton *button);
Resolved in https://github.com/stblr/mkw-sp/pull/401/commits/d9206b7315a4259150cd8d98bc4e72216ef1998d.

2022-09-12 06:40 UTC, vabold commented on payload/sp/cs/RoomServer.hh
> +        s32 vehicleId;
Resolved in https://github.com/stblr/mkw-sp/pull/401/commits/d9206b7315a4259150cd8d98bc4e72216ef1998d.

2022-09-12 06:40 UTC, vabold commented on payload/sp/cs/RoomServer.hh
> +    bool onReceiveProperties(u32 playerId, s32 characterId, s32 vehicleId, bool driftIsAuto);
Resolved in https://github.com/stblr/mkw-sp/pull/401/commits/d9206b7315a4259150cd8d98bc4e72216ef1998d.

2022-09-12 06:43 UTC, vabold commented on payload/game/ui/page/DriftSelectPage.cc
> +}
I took a stab at this in https://github.com/stblr/mkw-sp/pull/401/commits/d9206b7315a4259150cd8d98bc4e72216ef1998d. I do not agree that we should send all of the data at once on the first race, but I do agree that we should send it all at once in future races. We will likely need to have a discussion on how to proceed with how the server distributes course roulette information before this PR is complete.

2022-09-13 05:46 UTC, vabold commented on payload/game/ui/page/DriftSelectPage.cc
> +}
Resolved in https://github.com/stblr/mkw-sp/pull/401/commits/7a1cd07908c5a8e5e57bb49ab2d5ec420265e909. We have a solid plan for handling the roulette for the next task.

2022-09-13 05:49 UTC, stblr approved these changes

2022-09-13 05:50 UTC, merged