Broadcast a client's region line color on room join
stblr/mkw-sp pull request #406
Opened 2022-09-13 15:25 UTC by MikeIsAStar

2022-09-13 18:19 UTC, vabold commented on payload/game/ui/FriendMatchingPage.hh
> +#include "game/ui/ctrl/CtrlMenuDummyBack.hh"
Subfolder includes should go after direct ones.

2022-09-13 18:25 UTC, vabold requested changes
Aside from formatting, LGTM.

2022-09-13 18:25 UTC, vabold commented on payload/game/ui/FriendMatchingPage.hh
> +#include "game/ui/ctrl/CtrlMenuDummyBack.hh"
Subfolder includes should go after direct ones.

2022-09-13 18:25 UTC, vabold commented on payload/game/ui/FriendMatchingPage.hh
> +    H<YesNoPage> m_onCloseConfirm{this, &FriendMatchingPage::onCloseConfirm};
Missing whitespace on structure initialization.

2022-09-13 18:25 UTC, vabold commented on payload/game/ui/FriendRoomBackPage.cc
> +    m_queue.push(Join{mii, location, latitude, longitude, regionLineColor});
Missing whitespace on structure initialization.

2022-09-13 18:25 UTC, vabold commented on payload/game/ui/FriendRoomBackPage.cc
> +        m_queue.push(Leave{playerId});
Missing whitespace on structure initialization.

2022-09-13 18:25 UTC, vabold commented on payload/game/ui/FriendRoomBackPage.cc
> +        m_queue.push(Comment{playerId, messageId});
Missing whitespace on structure initialization.

2022-09-13 18:25 UTC, vabold commented on payload/game/ui/FriendRoomBackPage.cc
> +    m_queue.push(Settings{settings});
Missing whitespace on structure initialization.

2022-09-13 18:25 UTC, vabold commented on payload/game/ui/FriendRoomBackPage.hh
> +#include "game/ui/ctrl/CtrlMenuPageTitleText.hh"
Subfolder includes should go after direct ones.

2022-09-13 18:25 UTC, vabold commented on payload/sp/cs/RoomServer.cc
> +    m_players[m_playerCount] = {clientId, *mii, location, latitude, longitude, regionLineColor,
Missing whitespace on structure initialization.

2022-09-13 18:25 UTC, vabold commented on payload/sp/cs/RoomServer.cc
> +    m_commentQueue.push(Comment{playerId, messageId});
Missing whitespace on structure initialization.

2022-09-15 21:14 UTC, stblr approved these changes

2022-09-15 21:16 UTC, merged