Implement the 'Region Line Color' setting
stblr/mkw-sp pull request #420
Opened 2022-10-03 20:30 UTC by MikeIsAStar

2022-10-03 20:49 UTC, stblr requested changes

2022-10-03 20:49 UTC, stblr commented on payload/game/ui/ctrl/CtrlRaceNameBalloon.cc
> -#include "game/ui/page/RacePage.hh"
This should be controlled by `SortIncludes` in clang-format.

2022-10-03 20:49 UTC, stblr commented on payload/game/ui/ctrl/CtrlRaceNameBalloon.cc
> +                1);
Maybe make a temporary because that auto-formatting is ugly.

2022-10-04 15:05 UTC, MikeIsAStar commented on payload/game/ui/ctrl/CtrlRaceNameBalloon.cc
> -#include "game/ui/page/RacePage.hh"
Resolved in commit [8a01170](https://github.com/stblr/mkw-sp/pull/420/commits/8a01170d08cdcf172924fe29faa67a9d936bb200).

2022-10-04 15:05 UTC, MikeIsAStar commented on payload/game/ui/ctrl/CtrlRaceNameBalloon.cc
> +                1);
Resolved in commit [08a4e81](https://github.com/stblr/mkw-sp/pull/420/commits/08a4e81afbc9ea009a9be8a4048ce9ea3c9b8d6d).

2022-10-04 18:13 UTC, stblr approved these changes

2022-10-04 18:14 UTC, merged