Implement course voting
stblr/mkw-sp pull request #423
Opened 2022-10-08 05:19 UTC by vabold

Aims to solve `Choose character/vehicle/drift` and `Vote for a track` in #382.

2022-10-08 05:23 UTC, vabold commented
To do:
- [ ] Add "submitted" check from RoomClient in `RoulettePage::calcPlayer`
- [ ] Set Mii picture in `RoulettePage::VoteControl::onNewVote`
- [ ] Sync player order in `VotingBackPage::onInit`

To fix:
- [ ] Frame modulo check in `RoulettePage::beforeCalc` always passes

2022-10-24 21:00 UTC, stblr requested changes

2022-10-24 21:00 UTC, stblr commented on payload/game/ui/Page.hh
> +    u8 _0d[0x10 - 0xd];
Can be reverted.

2022-10-24 21:00 UTC, stblr commented on protobuf/Room.proto
> +        Vote     vote     = 8;
Not very convinced about the names but I don't have a specific suggestion.

2022-10-24 21:00 UTC, stblr commented on payload/sp/cs/RoomClient.cc
> +bool RoomClient::onReceiveVote(Handler &handler, RoomEvent event) {
Please validate the received event.

2022-10-24 21:00 UTC, stblr commented on payload/game/ui/VotingBackPage.hh
> +    bool m_submitted = false;
What are negative values used for?

2022-10-24 21:00 UTC, stblr commented on payload/game/ui/page/CupSelectPage.S
> +    lwz r29, 0x23d8(r3) // Original instruction
Does this work on non-PAL?

2022-10-24 21:00 UTC, stblr commented on payload/game/ui/page/CupSelectPage.S
> +    lfs f1, -0x2c3c(r4)
And this?

2022-10-24 21:00 UTC, stblr commented on payload/game/ui/RoulettePage.cc
> +        nullptr, "Roulette", "Unselected", "Selected", "Decide", nullptr};
Is clang-format unhappy if you put one element per line?

2022-10-24 21:00 UTC, stblr commented on payload/game/ui/RoulettePage.hh
> +    s8 m_playerOrder[12];
Why not just an array of booleans?

2022-10-24 21:00 UTC, stblr commented on payload/game/ui/RoulettePage.hh
> +    s32 m_selectedTrackMessageId;
Why not `u32`?

2022-10-24 21:00 UTC, stblr commented on payload/game/ui/UIControl.hh
> +    void setAnimation(u32 groupId, u32 animationId, f32 frame) { m_animator.getGroup(groupId)->setAnimation(animationId, frame); }
This can probably be removed, and replaced with helper functions in `VoteControl` given the usage.

2022-10-24 21:02 UTC, vabold commented on protobuf/Room.proto
> +        Vote     vote     = 8;
I could not think of better names. `Pulse` and `Info`?

2022-10-24 21:04 UTC, vabold commented on payload/game/ui/RoulettePage.cc
> +        nullptr, "Roulette", "Unselected", "Selected", "Decide", nullptr};
Yes.

2022-10-24 21:05 UTC, stblr commented on payload/game/ui/RoulettePage.cc
> +        nullptr, "Roulette", "Unselected", "Selected", "Decide", nullptr};
Consider adding `// clang-format off` and `// clang-format on` guards then.

2022-10-24 21:06 UTC, vabold commented on payload/game/ui/RoulettePage.hh
> +    s8 m_playerOrder[12];
We use the values stored in the order to get the player ID. Lines 167, 176, and 188.

2022-10-24 21:07 UTC, vabold commented on payload/game/ui/UIControl.hh
> +    void setAnimation(u32 groupId, u32 animationId, f32 frame) { m_animator.getGroup(groupId)->setAnimation(animationId, frame); }
I disagree - this is not specific to `VoteControl` and has demonstrable applications in other controls in the base game.

2022-10-24 21:07 UTC, stblr commented on protobuf/Room.proto
> +        Vote     vote     = 8;
I'm fine with anything with the `Select` prefix, including those.

2022-10-24 21:07 UTC, stblr commented on payload/game/ui/UIControl.hh
> +    void setAnimation(u32 groupId, u32 animationId, f32 frame) { m_animator.getGroup(groupId)->setAnimation(animationId, frame); }
Such as?

2022-10-24 21:11 UTC, stblr commented on payload/game/ui/UIControl.hh
> +    void setAnimation(u32 groupId, u32 animationId, f32 frame) { m_animator.getGroup(groupId)->setAnimation(animationId, frame); }
AFAIK all of these are called by the controls themselves.

2022-10-24 21:13 UTC, riidefi commented on payload/game/ui/Page.hh
> +    s32 frame() { return m_frame; }
Should be a const member function

2022-10-24 21:17 UTC, riidefi commented on payload/game/ui/RoulettePage.cc
> +        f32 delta = m_timeDelta - 0.001;
Use the f suffix (e.g. 0.001f) to make these literals floats not doubles.

2022-10-24 21:20 UTC, riidefi commented on payload/sp/cs/RoomServer.hh
> +    bool m_voted[12] = {};
Prefer std::bitset<12>

2022-10-24 21:28 UTC, vabold commented on payload/game/ui/UIControl.hh
> +    void setAnimation(u32 groupId, u32 animationId, f32 frame) { m_animator.getGroup(groupId)->setAnimation(animationId, frame); }
To clarify, the issue was `setAnimation` being public. `setAnimation` already exists in UIAnimator as well, so I will add the relevant helper functions to VoteControl and remove the function in LayoutUIControl.

2022-10-24 21:28 UTC, riidefi commented on payload/game/ui/RoulettePage.cc
> +    }
m_playerOrder.fill(-1) if you make it a std::array

2022-10-24 21:29 UTC, riidefi commented on payload/game/ui/RoulettePage.cc
> +    }
ditto

2022-10-24 21:37 UTC, vabold commented on payload/game/ui/RoulettePage.cc
> +        f32 delta = m_timeDelta - 0.001;
`0.001f` is required on `f32` assignment?

2022-10-24 22:03 UTC, vabold commented on payload/game/ui/VotingBackPage.hh
> +    bool m_submitted = false;
In the base game, -1 is used to represent a random course.

2022-10-25 05:33 UTC, vabold commented on payload/game/ui/Page.hh
> +    s32 frame() { return m_frame; }
I agree. GCC does not agree.

2022-10-25 05:45 UTC, vabold commented on payload/game/ui/Page.hh
> +    u8 _0d[0x10 - 0xd];
Resolved in https://github.com/stblr/mkw-sp/pull/423/commits/5f4a18501e7ad37d6d42f4aaafa1eab4681b9f57.

2022-10-25 05:45 UTC, vabold commented on protobuf/Room.proto
> +        Vote     vote     = 8;
Resolved in https://github.com/stblr/mkw-sp/pull/423/commits/5f4a18501e7ad37d6d42f4aaafa1eab4681b9f57.

2022-10-25 05:45 UTC, vabold commented on payload/sp/cs/RoomClient.cc
> +bool RoomClient::onReceiveVote(Handler &handler, RoomEvent event) {
Resolved in https://github.com/stblr/mkw-sp/pull/423/commits/5f4a18501e7ad37d6d42f4aaafa1eab4681b9f57.

2022-10-25 05:46 UTC, vabold commented on payload/game/ui/VotingBackPage.hh
> +    bool m_submitted = false;
Unsigned player count in https://github.com/stblr/mkw-sp/pull/423/commits/5f4a18501e7ad37d6d42f4aaafa1eab4681b9f57.

2022-10-25 05:47 UTC, vabold commented on payload/game/ui/page/CupSelectPage.S
> +    lwz r29, 0x23d8(r3) // Original instruction
`CupSelectPage_onRefocus` should work on non-PAL, yes.

2022-10-25 05:47 UTC, vabold commented on payload/game/ui/page/CupSelectPage.S
> +    lfs f1, -0x2c3c(r4)
Resolved in https://github.com/stblr/mkw-sp/pull/423/commits/5f4a18501e7ad37d6d42f4aaafa1eab4681b9f57.

2022-10-25 05:47 UTC, vabold commented on payload/game/ui/RoulettePage.cc
> +        nullptr, "Roulette", "Unselected", "Selected", "Decide", nullptr};
Resolved in https://github.com/stblr/mkw-sp/pull/423/commits/5f4a18501e7ad37d6d42f4aaafa1eab4681b9f57.

2022-10-25 05:47 UTC, vabold commented on payload/game/ui/RoulettePage.hh
> +    s32 m_selectedTrackMessageId;
Resolved in https://github.com/stblr/mkw-sp/pull/423/commits/5f4a18501e7ad37d6d42f4aaafa1eab4681b9f57.

2022-10-25 05:48 UTC, vabold commented on payload/game/ui/UIControl.hh
> +    void setAnimation(u32 groupId, u32 animationId, f32 frame) { m_animator.getGroup(groupId)->setAnimation(animationId, frame); }
Resolved in https://github.com/stblr/mkw-sp/pull/423/commits/5f4a18501e7ad37d6d42f4aaafa1eab4681b9f57.

2022-10-25 05:48 UTC, vabold commented on payload/game/ui/RoulettePage.cc
> +        f32 delta = m_timeDelta - 0.001;
Resolved in https://github.com/stblr/mkw-sp/pull/423/commits/5f4a18501e7ad37d6d42f4aaafa1eab4681b9f57.

2022-10-25 05:48 UTC, vabold commented on payload/sp/cs/RoomServer.hh
> +    bool m_voted[12] = {};
Resolved in https://github.com/stblr/mkw-sp/pull/423/commits/5f4a18501e7ad37d6d42f4aaafa1eab4681b9f57.

2022-10-25 05:48 UTC, vabold commented on payload/game/ui/RoulettePage.cc
> +    }
Removed unnecessary assignment in ctor in https://github.com/stblr/mkw-sp/pull/423/commits/5f4a18501e7ad37d6d42f4aaafa1eab4681b9f57.

2022-10-25 05:48 UTC, vabold commented on payload/game/ui/RoulettePage.cc
> +    }
Resolved in https://github.com/stblr/mkw-sp/pull/423/commits/5f4a18501e7ad37d6d42f4aaafa1eab4681b9f57.

2022-10-25 08:15 UTC, stblr commented on payload/game/ui/RoulettePage.hh
> +    s8 m_playerOrder[12];
It's just compared against 0.

2022-10-25 17:02 UTC, vabold commented
Back to draft. This PR will also introduce `RoomManager`, and merge the separate handlers into one class.

2022-10-26 04:52 UTC, vabold commented on payload/game/ui/Page.hh
> +    s32 frame() { return m_frame; }
Resolved in https://github.com/stblr/mkw-sp/pull/423/commits/375f2aac65c5e59ab4c32de254c57adf08611391.

2022-10-26 04:53 UTC, vabold commented
Going to bed - can I get an early look at `RoomManager` before implementing player order sync?

2022-10-26 05:44 UTC, riidefi commented on payload/game/ui/page/CourseSelectPage.S
> +    stb r4, 0x136(r3)
Is this safe?

2022-10-26 05:59 UTC, riidefi commented on payload/game/ui/VotingBackPage.cc
> +VotingBackPage::VotingBackPage() : m_handler(*this) {}
Because you take a reference here, VotingBackPage's copy/move ctors will create stale references and should be disabled.

2022-10-26 06:09 UTC, riidefi commented on payload/sp/cs/RoomManager.cc
> +    size_t size;
Style: move this down as far as possible.

2022-10-26 06:10 UTC, riidefi commented on payload/game/ui/VotingBackPage.hh
> +    bool m_selected[12];
Generally prefer std::bitset

2022-10-26 18:31 UTC, stblr requested changes

2022-10-28 16:18 UTC, vabold commented on payload/game/ui/page/CourseSelectPage.S
> +    stb r4, 0x136(r3)
Resolved in https://github.com/stblr/mkw-sp/pull/423/commits/3088fdd828f7353264e468961c4d42569e9c96b3.

2022-10-28 16:18 UTC, vabold commented on payload/game/ui/VotingBackPage.cc
> +VotingBackPage::VotingBackPage() : m_handler(*this) {}
Resolved in https://github.com/stblr/mkw-sp/pull/423/commits/3088fdd828f7353264e468961c4d42569e9c96b3.

2022-10-28 16:18 UTC, vabold commented on payload/sp/cs/RoomManager.cc
> +    size_t size;
Resolved in https://github.com/stblr/mkw-sp/pull/423/commits/3088fdd828f7353264e468961c4d42569e9c96b3.

2022-10-28 16:19 UTC, vabold commented on payload/game/ui/VotingBackPage.hh
> +    bool m_selected[12];
Resolved in https://github.com/stblr/mkw-sp/pull/423/commits/3088fdd828f7353264e468961c4d42569e9c96b3.

2022-10-28 16:19 UTC, vabold commented on payload/game/ui/page/CourseSelectPage.S
> +PATCH_B_END(CourseSelectPage_afterCalc, 0x44)
Resolved in https://github.com/stblr/mkw-sp/pull/423/commits/3088fdd828f7353264e468961c4d42569e9c96b3.

2022-10-28 16:21 UTC, vabold commented on payload/sp/cs/RoomClient.hh
> +            std::optional<bool> driftIsAuto);
Potentially resolved in https://github.com/stblr/mkw-sp/pull/423/commits/3088fdd828f7353264e468961c4d42569e9c96b3. I could not get a simple instantiation of `std::optional<Player::Properties>` to work, so I moved that to `RoomManager::createPlayerProperties`.

2022-10-28 20:43 UTC, vabold reviewed
Remove `std::optional` as much as possible and simply validate that the properties do not change in `RoomServer::validateProperties`.

2022-10-28 20:43 UTC, vabold commented on payload/game/ui/GlobePage.S
> +    nop
stblr: Add explanation comment.

2022-10-28 20:43 UTC, vabold commented on payload/game/ui/RoulettePage.cc
> +    }
Invert `m_isBattle` conditions.

Read from `SP::RoomManager::m_gamemode` for generalized sections (i.e. `SectionId::VotingServer`).

2022-10-28 20:43 UTC, vabold commented on payload/game/ui/RoulettePage.cc
> +    }
Initialize page children with a consistent order with other pages.

- Insert
- Load
- Handlers (not applicable here)

2022-10-28 20:43 UTC, vabold commented on payload/game/ui/RoulettePage.cc
> +    m_stage = Stage::Selecting;
Call `ResourceManager::preloadCourseAsync` here as well.

2022-10-28 20:43 UTC, vabold commented on payload/game/ui/RoulettePage.cc
> +    }
Replace this with a check for bitset `m_processed`, which should be set to true after `m_currentPlayerIdx` is incremented.

2022-10-28 20:43 UTC, vabold commented on payload/game/ui/RoulettePage.cc
> +} // namespace UI
Newline.

2022-10-28 20:43 UTC, vabold commented on payload/game/ui/RoulettePage.hh
> +    u32 m_selectedTrackMessageId;
Remove `m_selectedTrackMessageId`.

2022-10-28 20:43 UTC, vabold commented on payload/game/ui/VotingBackPage.cc
> +    }
Replace this with the new `RoomManager` class.

2022-10-28 20:43 UTC, vabold commented on payload/game/ui/page/CourseSelectPage.S
> +PATCH_B_START(CourseSelectPage_onSelect, 0xf4)
Add comment - "Submit vote for online".

2022-10-28 20:43 UTC, vabold commented on payload/game/ui/page/CupSelectPage.S
> +PATCH_B_START(CupSelectPage_afterCalc, 0x5c)
Add comment - "Temporary: remove timer and unnecessary page code".

2022-10-28 20:43 UTC, vabold commented on payload/game/ui/page/CupSelectPage.S
> +PATCH_BL_START(CupSelectPage_onRefocus, 0x1c)
Add comment - "Submit vote for online".

2022-10-29 06:55 UTC, vabold commented on payload/game/ui/page/CupSelectPage.S
> +PATCH_BL_START(CupSelectPage_onRefocus, 0x1c)
Resolved in https://github.com/stblr/mkw-sp/pull/423/commits/418093830efd5ab995fe3e3eea92fdc2132ce9f8.

2022-10-29 06:55 UTC, vabold commented on payload/game/ui/page/CupSelectPage.S
> +PATCH_B_START(CupSelectPage_afterCalc, 0x5c)
Resolved in https://github.com/stblr/mkw-sp/pull/423/commits/418093830efd5ab995fe3e3eea92fdc2132ce9f8.

2022-10-29 06:55 UTC, vabold commented on payload/game/ui/page/CourseSelectPage.S
> +PATCH_B_START(CourseSelectPage_onSelect, 0xf4)
Resolved in https://github.com/stblr/mkw-sp/pull/423/commits/418093830efd5ab995fe3e3eea92fdc2132ce9f8.

2022-10-29 06:55 UTC, vabold commented on payload/game/ui/VotingBackPage.cc
> +    }
Resolved in https://github.com/stblr/mkw-sp/pull/423/commits/418093830efd5ab995fe3e3eea92fdc2132ce9f8.

2022-10-29 06:56 UTC, vabold commented on payload/game/ui/RoulettePage.hh
> +    u32 m_selectedTrackMessageId;
Resolved in https://github.com/stblr/mkw-sp/pull/423/commits/418093830efd5ab995fe3e3eea92fdc2132ce9f8.

2022-10-29 06:56 UTC, vabold commented on payload/game/ui/RoulettePage.cc
> +} // namespace UI
Resolved in https://github.com/stblr/mkw-sp/pull/423/commits/418093830efd5ab995fe3e3eea92fdc2132ce9f8.

2022-10-29 06:56 UTC, vabold commented on payload/game/ui/RoulettePage.cc
> +    }
Resolved in https://github.com/stblr/mkw-sp/pull/423/commits/418093830efd5ab995fe3e3eea92fdc2132ce9f8.

2022-10-29 06:56 UTC, vabold commented on payload/game/ui/RoulettePage.cc
> +    m_stage = Stage::Selecting;
Resolved in https://github.com/stblr/mkw-sp/pull/423/commits/418093830efd5ab995fe3e3eea92fdc2132ce9f8.

2022-10-29 06:56 UTC, vabold commented on payload/game/ui/RoulettePage.cc
> +    }
Resolved in https://github.com/stblr/mkw-sp/pull/423/commits/418093830efd5ab995fe3e3eea92fdc2132ce9f8.

2022-10-29 06:56 UTC, vabold commented on payload/game/ui/RoulettePage.cc
> +    }
Resolved in https://github.com/stblr/mkw-sp/pull/423/commits/418093830efd5ab995fe3e3eea92fdc2132ce9f8.

2022-10-29 06:56 UTC, vabold commented on payload/game/ui/GlobePage.S
> +    nop
Resolved in https://github.com/stblr/mkw-sp/pull/423/commits/418093830efd5ab995fe3e3eea92fdc2132ce9f8.

2022-10-29 06:56 UTC, vabold commented on payload/sp/cs/RoomClient.hh
> +            std::optional<bool> driftIsAuto);
Resolved in https://github.com/stblr/mkw-sp/pull/423/commits/418093830efd5ab995fe3e3eea92fdc2132ce9f8.

2022-10-29 06:58 UTC, riidefi commented on payload/game/ui/RoulettePage.cc
> +const char *animInfo[] = {
`static` or put in empty namespace (this will break if multiple files have an array named animInfo[] in the UI namespace).

2022-10-29 07:02 UTC, riidefi commented on payload/game/ui/page/CupSelectPage.S
> +    stw r0, 0x3e8(r3)
Is this right? Shouldn't r3 be either 0 or 1 (from getSubmitted()) at this point?

2022-10-29 07:07 UTC, vabold commented on payload/game/ui/RoulettePage.cc
> +const char *animInfo[] = {
Resolved in https://github.com/stblr/mkw-sp/pull/423/commits/92be2ec79a24697bba6cafadedc993a5f072f388.

2022-10-29 07:07 UTC, vabold commented on payload/game/ui/page/CupSelectPage.S
> +    stw r0, 0x3e8(r3)
Resolved in https://github.com/stblr/mkw-sp/pull/423/commits/d35f0e45c88d85eecdecbf8f0c4fde22090bd89c.

2022-10-29 08:28 UTC, stblr approved these changes

2022-10-29 08:28 UTC, merged