Add 3D checkpoint visualization
stblr/mkw-sp pull request #461
Opened 2022-11-06 06:13 UTC by riidefi

Footage: https://youtu.be/NSwiO4purMA

2022-11-06 07:18 UTC, vabold commented on assets/message/MenuSP_U.bmg.json5
> +        "string": "Debug overlay",
Capitalize "Overlay".

2022-11-06 07:20 UTC, riidefi commented on assets/message/MenuSP_U.bmg.json5
> +        "string": "Debug overlay",
Fixed

2022-11-06 09:47 UTC, stblr requested changes

2022-11-06 09:47 UTC, stblr commented on payload/sp/settings/ClientSettings.cc
> +constexpr u32 MID_ENABLE = 10058;
We actually need one message per setting because of i18n.

2022-11-06 09:47 UTC, stblr commented on payload/sp/3d/Checkpoints.cc
> +    }
Any reason to have this rather than a static constant?

2022-11-06 09:47 UTC, stblr commented on payload/sp/3d/Checkpoints.cc
> +        mDlSize = 0xA0;
`std::size` or `std::array`

2022-11-06 09:47 UTC, stblr commented on payload/sp/3d/Checkpoints.cc
> +        alignas(32) static u8 CACHED_DL[] = {0x61, 0x28, 0x04, 0x90, 0x00, 0x61, 0xC0, 0x08, 0xA8,
If you have command annotations on hand, I think they should be added. Otherwise don't bother.

2022-11-06 10:53 UTC, riidefi commented on payload/sp/settings/ClientSettings.cc
> +constexpr u32 MID_ENABLE = 10058;
Do the three existing uses of each need to be changed too?

2022-11-06 10:54 UTC, stblr commented on payload/sp/settings/ClientSettings.cc
> +constexpr u32 MID_ENABLE = 10058;
Yes (not necessarily in this PR).

2022-11-06 23:48 UTC, riidefi commented on payload/sp/3d/Checkpoints.cc
> +    }
This would allow us to quickly swap the material via a setting in the future.

2022-11-07 20:16 UTC, stblr approved these changes

2022-11-07 20:16 UTC, merged