Add Mega TCs
stblr/mkw-sp pull request #466
Opened 2022-11-07 23:35 UTC by Hibyehello

This adds Mega TCs as an offline VS option

2022-11-08 00:24 UTC, vabold requested changes

2022-11-08 00:24 UTC, vabold commented on .gitignore
> +.DS_Store
Newline.

2022-11-08 00:24 UTC, vabold commented on payload/game/kart/KartMove.cc
> +}
Is this necessary?

2022-11-08 00:24 UTC, vabold commented on payload/game/kart/KartMove.cc
> +    if(setting == SP::ClientSettings::VSMegaClouds::Enable) {
Add whitespace after `if`.

2022-11-08 00:24 UTC, vabold commented on payload/game/kart/KartMove.hh
> +    void ActivateMega();
STYLE: lowercase the first letter of class method.

2022-11-08 00:24 UTC, vabold commented on payload/game/kart/KartMove.hh
> +    REPLACE bool ThunderActive(int timer, int param_3, int param_4);
Function can be called `activateTc`, and the method does not take in any parameters.

2022-11-08 00:24 UTC, vabold commented on payload/sp/settings/ClientSettings.cc
> +        .valueExplanationMessageIds = (u32[]) { 20037, 20036 },
Very minor change, but it would be nice if the ordering was consistent here.

`{ 20038, 20039 }` and `{ 20036, 20037 }`, with the explanation messages changed to reflect that.

2022-11-08 00:27 UTC, Gaberboo commented on payload/game/kart/KartMove.cc
> +}
Pretty sure it's not

2022-11-08 01:19 UTC, Hibyehello commented on payload/game/kart/KartMove.cc
> +}
I just copied and pasted that from other files

2022-11-08 01:22 UTC, Hibyehello commented on payload/game/kart/KartMove.hh
> +    REPLACE bool ThunderActive(int timer, int param_3, int param_4);
it does take params, at least for the vanilla functions

2022-11-08 03:51 UTC, vabold approved these changes
LGTM

2022-11-08 03:57 UTC, vabold requested changes

2022-11-08 03:57 UTC, vabold commented on payload/game/kart/KartMove.cc
> +    return true;
Declare the replaced function as bool and return the result.

2022-11-08 04:11 UTC, vabold approved these changes

2022-11-08 19:25 UTC, stblr requested changes

2022-11-08 19:25 UTC, stblr commented on payload/game/kart/KartMove.hh
> +    REPLACE bool activateTc();
We already use this name for another function in ghidra (when activating the cloud itself and not the lightning).

2022-11-08 19:25 UTC, stblr commented on payload/sp/settings/ClientSettings.hh
> +{
Brace style.

2022-11-08 19:25 UTC, stblr commented on payload/game/kart/KartMove.cc
No blank line here.

2022-11-08 22:08 UTC, Hibyehello commented on payload/game/kart/KartMove.hh
> +    REPLACE bool activateTc();
I'm not surprised, I've been trying to name it properly

2022-11-09 20:25 UTC, stblr approved these changes

2022-11-09 20:26 UTC, merged