Speedometer
stblr/mkw-sp pull request #467
Opened 2022-11-08 01:19 UTC by Gaberboo

Adds options for different speedometer metrics

2022-11-08 03:49 UTC, vabold requested changes

2022-11-08 03:49 UTC, vabold commented on assets/message/MenuSP_U.bmg.json5
> +    },
If possible, a better name could be used. "Terrain" implies more general KCL, not just moving water/road.

2022-11-08 03:49 UTC, vabold commented on payload/game/ui/ctrl/CtrlRaceSpeed.cc
> +    speed = std::min(speed, hardSpeedLimit);
Hard speed limit should not be applied to XYZ/XZ/Y, given that we are measuring more than the velocity.

2022-11-08 03:49 UTC, vabold commented on payload/game/ui/ctrl/CtrlRaceSpeed.cc
> +            {
We don't use braces for code in switch cases.

2022-11-08 03:49 UTC, vabold commented on payload/game/ui/ctrl/CtrlRaceSpeed.cc
> +            {
Same as above.

2022-11-08 05:09 UTC, vabold commented on assets/message/MenuSP_U.bmg.json5
> +    }
`},`

2022-11-08 05:11 UTC, riidefi commented on payload/game/ui/ctrl/CtrlRaceSpeed.cc
> +            {
It's needed to declare variables inside the scope. Should be fine as long as he runs clang-format here and fixes the indentation of the case labels/such.

2022-11-08 19:43 UTC, stblr commented on payload/game/ui/ctrl/CtrlRaceSpeed.cc
> +        setting = SP::ClientSettings::Speedometer::XYZ;
Do we want this for all settings?

2022-11-11 04:50 UTC, Gaberboo commented on assets/message/MenuSP_U.bmg.json5
> +        "string": "Internal + Moving Road",
I just liked moving road better

2022-11-11 04:51 UTC, Gaberboo commented on payload/game/ui/ctrl/CtrlRaceSpeed.cc
> +        setting = SP::ClientSettings::Speedometer::XYZ;
Yes

2022-11-11 18:57 UTC, stblr approved these changes

2022-11-11 18:57 UTC, merged