Adds a custom model and item box icon for Mega TCs.
stblr/mkw-sp pull request #475
Opened 2022-11-12 23:48 UTC by Zachruff

Model by Atlas
Icon by professorchaos

To do: add two breff effect files that accompany these visuals.

2022-11-12 23:56 UTC, vabold requested changes

2022-11-12 23:56 UTC, vabold commented on payload/game/system/DVDArchive.cc
> +            } */
Remove comment.

2022-11-12 23:56 UTC, vabold commented on payload/game/util/Registry.cc
> +            }
Merge conditions.

2022-11-12 23:56 UTC, vabold commented on payload/game/util/Registry.cc
> +            // pane, otehrwise go back to original function
"otehrwise"

I don't think we need a comment here, the code is fairly self-explanatory. Maybe "Return mega TC pane".

2022-11-12 23:56 UTC, vabold commented on payload/game/util/Registry.cc
> +    } // namespace Registry
Newline.

2022-11-12 23:56 UTC, vabold commented on payload/game/util/Registry.cc
> +        const char* getItemPane(u32 itemId, u32 count) {
Please run clang-format.

2022-11-12 23:56 UTC, vabold commented on payload/game/util/Registry.hh
> +const char* GetItemPane(u32 itemId, u32 count);
We do not need `GetItemPane`.

STYLE: `const char* getItemPane` should be `const char *getItemPane`.

2022-11-14 06:29 UTC, riidefi commented on payload/game/util/Registry.hh
> +const char *REPLACED(getItemPane)(u32 itemId, u32 count);
(Optional) Capitalize first letter to match other functions in this file.

2022-11-19 15:44 UTC, stblr approved these changes

2022-11-19 15:45 UTC, merged