Page tables
stblr/mkw-sp pull request #495
Opened 2022-11-25 22:44 UTC by Gaberboo

Resolves #445
Maps executable sections with a page table

2022-11-25 23:52 UTC, riidefi commented on payload/sp/security/PageTable.c
> +        for (size_t index = 0;pageTableMaps[index];index++) {
Run this file through clang-format again

2022-11-25 23:54 UTC, riidefi commented on payload/sp/security/PageTable.c
> +    for (size_t hashIndex = 0; hashIndex < (sizeof(hashArray) / sizeof(u32)); hashIndex++) {
```diff
- (sizeof(hashArray) / sizeof(u32))
+ ARRAY_SIZE(hashArray)
```

2022-11-26 00:04 UTC, riidefi commented on payload/sp/security/PageTable.c
> +            }
I'd pull out this linear search and unindent the block below:
```c
PageTableEntry *pte = nullptr;
for (size_t entryIndex = 0; entryIndex < 8; entryIndex++) {
    PageTableEntry *it= &pteg[entryIndex];
    if (!it->V) { pte = it; break; }
}
if (!pte) { continue; }
```
If we move this file to C++ we could write this as
```cpp
auto pte = std::find_if(pteg, pteg + 8, [](auto &x){ return !x.V; });
if (pte == pteg + 8) { continue; }
```

2022-11-26 00:10 UTC, riidefi commented on payload/sp/security/PageTable.c
> +        u32 index = ((hashArray[hashIndex] & (HTABMASK << 10)) | (hashArray[hashIndex] & 0x3FF)) << 6;
`offset` is probably a better name here given sizeof(PageTableEntry) > 1

2022-11-29 17:10 UTC, MikeIsAStar commented on payload/sp/security/PageTable.c
> +        for (size_t index = 0;pageTableMaps[index];index++) {
Resolved in commit [6e880f1](https://github.com/stblr/mkw-sp/pull/495/commits/6e880f1f8d09e43cccc045944ed8f9eaf5fee7db).

2022-11-29 17:10 UTC, MikeIsAStar commented on payload/sp/security/PageTable.c
> +    for (size_t hashIndex = 0; hashIndex < (sizeof(hashArray) / sizeof(u32)); hashIndex++) {
Resolved in commit [6e880f1](https://github.com/stblr/mkw-sp/pull/495/commits/6e880f1f8d09e43cccc045944ed8f9eaf5fee7db).

2022-11-29 17:10 UTC, MikeIsAStar commented on payload/sp/security/PageTable.c
> +            }
Resolved in commit [6e880f1](https://github.com/stblr/mkw-sp/pull/495/commits/6e880f1f8d09e43cccc045944ed8f9eaf5fee7db).

2022-11-29 17:10 UTC, MikeIsAStar commented on payload/sp/security/PageTable.c
> +        u32 index = ((hashArray[hashIndex] & (HTABMASK << 10)) | (hashArray[hashIndex] & 0x3FF)) << 6;
Resolved in commit [6e880f1](https://github.com/stblr/mkw-sp/pull/495/commits/6e880f1f8d09e43cccc045944ed8f9eaf5fee7db).

2022-11-30 06:05 UTC, riidefi commented on payload/sp/security/PageTable.cc
> +        return true;
Maybe pull out of loop

2022-11-30 06:08 UTC, riidefi commented on payload/sp/security/PageTable.cc
> +        for (u32 offset = 0; offset != size; offset += PAGE_SIZE) {
Maybe assert PAGE_SIZE divides size

2022-11-30 21:49 UTC, stblr commented on payload/sp/security/Memory.c
> +extern void InvalidateAllIBATs(void);
No need for `extern` here.

2022-12-10 14:39 UTC, stblr requested changes

2022-12-10 14:39 UTC, stblr commented on payload/sp/security/PageTable.cc
> +#include <algorithm>
https://github.com/stblr/mkw-sp/issues/245#issuecomment-1213490665

2022-12-10 14:39 UTC, stblr commented on payload/sp/security/PageTable.cc
> +typedef enum WIMG {
No need for `typedef` here and for the other definitions in C++.

2022-12-10 14:39 UTC, stblr commented on payload/sp/security/PageTable.cc
> +__attribute__((aligned(PAGE_TABLE_SIZE))) static char pageTable[PAGE_TABLE_SIZE];
`alignas`

2022-12-11 12:11 UTC, riidefi commented on payload/sp/security/PageTable.cc
> +    const PageTableEntry entry = {
Question: Are the reserved bits guaranteed to be zero here?

2022-12-11 19:42 UTC, Gaberboo commented on payload/sp/security/PageTable.cc
> +    const PageTableEntry entry = {
According to Ghidra, yes
`          entry[1] = (RPN & 0xfffff000) + offset | (*(uint *)((int)puVar6 + 0xc) & 0xf) << 3 |
                     *(uint *)((int)puVar6 + 0x10) & 3;`
offset is only ever set to multiples of 0x1000

2022-12-11 21:25 UTC, stblr approved these changes

2022-12-11 21:27 UTC, merged

2022-12-11 22:04 UTC, riidefi commented on payload/sp/security/PageTable.cc
> +    const PageTableEntry entry = {
My question was in a moral--not observational--sense. But it does seem they are guaranteed to be zero by the standard:
> If there are fewer initializers in a brace-enclosed list than there are elements or members of an aggregate, or fewer characters in a string literal used to initialize an array of known size than there are elements in the array, the remainder of the aggregate shall be initialized implicitly the same as objects that have static storage duration.