Added mirror to TTs
stblr/mkw-sp pull request #536
Opened 2023-01-10 19:00 UTC by henrymkw

2023-01-10 19:06 UTC, vabold requested changes
Here is my incredibly useful PR review.

2023-01-10 19:06 UTC, vabold commented on payload/egg/core/eggScene.hh
> +
Use const qualifiers on these functions.

2023-01-10 19:06 UTC, vabold commented on payload/egg/core/eggSceneManager.cc
> +    else {
Formatting.

2023-01-10 19:06 UTC, vabold commented on payload/game/system/GhostWriter.cc
> +}
Formatting.

2023-01-10 19:06 UTC, vabold commented on payload/game/system/GhostWriter.cc
> +}
Add newline.

2023-01-10 19:06 UTC, vabold commented on payload/game/system/GhostWriter.hh
> +}
Add newline.

2023-01-10 19:06 UTC, vabold commented on payload/game/system/GhostWriter.hh
> +    private:
Formatting.

2023-01-10 19:06 UTC, vabold commented on payload/game/system/RaceConfig.cc
> +    }
Formatting.

2023-01-10 19:10 UTC, riidefi commented on payload/egg/core/eggScene.hh
> +
SP style is more like ```cpp
u32 sceneID() const {
    return m_sceneID;
}```

2023-01-10 19:13 UTC, riidefi commented
Nice work!

2023-01-10 19:52 UTC, stblr requested changes

2023-01-10 19:52 UTC, stblr commented on payload/egg/core/eggScene.hh
> +    u32 sceneID;
`m_`

2023-01-10 19:52 UTC, stblr commented on payload/egg/core/eggSceneManager.hh
> +    Scene *currScene;
`m_`

2023-01-10 19:52 UTC, stblr commented on payload/egg/core/eggSceneManager.cc
> +
https://github.com/stblr/mkw-sp/issues/245#issuecomment-1213490665

2023-01-10 19:52 UTC, stblr commented on payload/game/system/GhostWriter.cc
> +}
https://github.com/stblr/mkw-sp/issues/245#issuecomment-1213490665

2023-01-10 19:52 UTC, stblr commented on payload/game/system/InputManager.cc
> +#include "RaceConfig.hh"
https://github.com/stblr/mkw-sp/issues/245#issuecomment-1213490665

2023-01-10 19:52 UTC, stblr commented on payload/game/system/RaceConfig.cc
> +#include <sp/settings/ClientSettings.hh>
https://github.com/stblr/mkw-sp/issues/245#issuecomment-1213490665

2023-01-10 19:52 UTC, stblr commented on payload/game/system/GhostFile.hh
>      static constexpr u32 VERSION = 4;
Please bump, and adapt `SPFooter::checkSize`.

2023-01-12 21:28 UTC, stblr approved these changes

2023-01-12 21:37 UTC, merged