Get battle mode playable again
stblr/mkw-sp pull request #540
Opened 2023-01-15 22:39 UTC by GnomedDev

Currently, battle mode is in quite a sorry state with

- [ ] Kart Select not rendering any kart other than standard kart and bike
- [x] MKW-SP crashing on loading battle mode in `getPlayerIdx` due to a null pointer
- [x] MKW-SP showing wrong UI (VS) for demo
- [ ] MKW-SP showing wrong UI (VS) for in race
- [ ] MKW-SP crashing after battle mode ends due to results screen failing to load.

This "tracking PR" aims to fix all these issues, and will be marked ready once everything is working to at least vanilla levels.

2023-01-16 17:23 UTC, GnomedDev commented
Fixing kart select is going to be harder than I thought. It is currently broken due to the page merging effort (the UI flow has been changed to mimic VS, then branch back to battle mode when loading demo) as the normal `VehicleSelectPage` doesn't contain the code `onActivate` for calling `0x80860bf0` and setting the `LayoutUiControl`s up correctly, which even if that is fixed will probably only solve the missing thumbnails and not the missing model and spinning animation.

2023-01-17 19:40 UTC, vabold requested changes

2023-01-17 19:40 UTC, vabold commented on payload/game/enemy/EnemyManager.cc
> +}
Static methods should be PascalCase and not camelCase.

2023-01-17 19:40 UTC, vabold commented on payload/game/enemy/EnemyManager.hh
> +    REPLACE static bool isOfflineBattle(void);
Static methods should be defined below non-static members.

2023-01-17 19:40 UTC, vabold commented on payload/game/system/RaceConfig.cc
> +        assert(false);
I would add a `SP_LOG` call directly above the assert so it's a little clearer what the problem is.

2023-01-17 19:40 UTC, vabold commented on assets/message/MenuSP_U.bmg.json5
> +    },
If this is for battle mode, it should be "Battles", not "Races".

2023-01-17 19:40 UTC, vabold commented on payload/game/ui/page/ResultTeamTotalPage.cc
> +    }
I would rewrite this to be one line, but you don't have to.
`return raceScenario.isBattle() ? PageId::AfterBtMenu : PageId::AfterVsMenu;`

2023-01-17 19:40 UTC, vabold commented on payload/game/util/Registry.cc
> +}
This returns a boolean.

2023-01-20 19:32 UTC, stblr requested changes

2023-01-20 19:32 UTC, stblr commented on assets/message/Menu_E.bmg.json5
> +        "string": "Settings",
How hard would it be to use new ids?

2023-01-20 19:32 UTC, stblr commented on symbols.txt
> +0x80739740 _ZN5Enemy12EnemyManager15IsOfflineBattleEv
Please keep them ordered.

2023-01-20 19:32 UTC, stblr commented on assets/message/Menu_E.bmg.json5
> +        "string": "Change settings for this licence.",
Same

2023-01-20 19:32 UTC, stblr commented on payload/sp/settings/ClientSettings.hh
> +enum class Classes {
Why plural? Because of the "mixed" option?

2023-01-20 19:32 UTC, stblr commented on payload/game/ui/page/BattleModeSelectPage.hh
> +
No blank line here.

2023-01-20 19:32 UTC, stblr commented on payload/game/ui/page/BattleModeSelectPage.cc
> +}
https://github.com/stblr/mkw-sp/issues/245#issuecomment-1213490665

2023-01-20 19:40 UTC, GnomedDev commented on payload/game/ui/Section.cc
> +    loadTHP();
256 bytes of heap, if it isn't already initialized

2023-01-20 19:44 UTC, stblr commented on payload/game/ui/Section.cc
> +    loadTHP();
Actually, isn't it more like 3 MiB (in 80529ac4)?

2023-01-20 20:08 UTC, GnomedDev commented on payload/game/ui/Section.cc
> +    loadTHP();
oh huh, but it should be loaded for most sections anyway, what do you suggest I do?

2023-01-20 20:13 UTC, stblr commented on payload/game/ui/Section.cc
> +    loadTHP();
The sections with the globe background (which uses tons of memory), race sections as well as other sections like license settings don't use them. I would suggest to just use `REPLACE`/`REPLACED` on the `onInit` function of offending pages.

2023-01-20 20:40 UTC, GnomedDev commented on payload/game/ui/Section.cc
> +    loadTHP();
The problem is that as more `Page`s are rewritten or removed they may forget to load the `THPManager` as it isn't required for the Page, as happened in this example, as Nintendo didn't load it for all the `Page`s it used. I'd prefer a blacklist of memory intensive pages.

2023-01-20 21:35 UTC, stblr commented on payload/game/ui/Section.cc
> +    loadTHP();
A blacklist would have the same problem as the current "whitelist", except that it would silently waste an obscene amount of memory or OOM at a random place.

2023-01-20 23:22 UTC, GnomedDev commented on payload/game/system/RaceConfig.cc
> -            assert(screenId < screenCount);
That assert fired on starting split screen matches, and removing it didn't break anything (tested all screen counts and vs single)

2023-01-20 23:24 UTC, GnomedDev commented on assets/message/Menu_E.bmg.json5
> +        "string": "Settings",
Would need a rewrite of BattleModeSelectPage::onInit, or onActivate, not sure. I don't see what's wrong with just replacing the old text as this would also change if that ID was reused.

2023-01-21 13:08 UTC, stblr commented on assets/message/Menu_E.bmg.json5
> +        "string": "Settings",
The issue is that for other languages, you get an incorrect text which is worse than an untranslated one. I _think_ that using the existing id and putting it in MenuSP_U would work but that would need to be tested.

2023-01-22 22:01 UTC, stblr approved these changes

2023-01-22 22:02 UTC, merged