gameserver: Implement chat
stblr/mkw-sp pull request #548
Opened 2023-01-21 01:53 UTC by GnomedDev

Added support for forwarding the Comment message, while properly adding anyhow, tracing, and documentation for helping the development experience.

2023-01-21 15:13 UTC, stblr requested changes

2023-01-21 15:13 UTC, stblr commented on tools/gameserver/src/client.rs
> +};
The aliases are fine, but I would prefer if they were used everywhere and not just in this file.

2023-01-21 15:13 UTC, stblr commented on tools/gameserver/src/client.rs
> +            _ => unimplemented!("Request type not implemented!")
This allows the client to crash the server. We rather want the default case to disconnect the client (e.g.  if a Join request is received).

2023-01-21 15:13 UTC, stblr commented on tools/gameserver/src/server.rs
> +    pub inner: usize,
I would suggest to add a getter instead, as the value should never be changed after construction.

2023-01-21 15:13 UTC, stblr commented on tools/gameserver/src/server.rs
> +                self.tx.send(Event::Forward { inner: room_event::Event::Comment(inner) });
Please explicitly ignore the error here.

2023-01-21 15:13 UTC, stblr commented on tools/gameserver/src/client.rs
> +    /// The channel to recieve broadcasted [`Event`]s from the server.
receive

2023-01-21 15:13 UTC, stblr commented on tools/gameserver/Cargo.toml
> +anyhow = "1.0.68"
What's the best practice here, since libhydrogen re-exports it?

2023-01-21 15:16 UTC, stblr commented
There is a leftover `error.rs` file.

2023-01-21 15:36 UTC, GnomedDev commented on tools/gameserver/Cargo.toml
> +anyhow = "1.0.68"
Adding the dependency to our project will just mean that as long as anyhow doesn't go above 1.x, it just allows our crate access to the full anyhow crate instead of just the macro that libhydrogen re-exports. It also means that libhydrogen can have a breaking upgrade which removes anyhow usage without breaking our crate while upgrading the dependency.

2023-01-22 09:34 UTC, stblr approved these changes

2023-01-22 09:34 UTC, merged