Initial implementation of matchmaking
stblr/mkw-sp pull request #561
Opened 2023-01-30 23:49 UTC by GnomedDev

This PR:

- Creates a new tool, `matchmaking`, which is built to accept `TCP` connections from `MKW-SP` and direct them towards the most populated room, or creates a room on the least used `gameserver`
- Modifies `gameserver` to handle multiple rooms, and if the correct command line arguments are passed, connect to an existing `matchmaking` server as part of the matchmaking pool.
- Splits off `gameserver`'s `async_stream.rs` into it's own library.
- Adds a very basic UI Page for matchmaking, being triggered by entering `0` into the direct connection box and automatically asking a matchmaking server on localhost to finding an open room.

This is the start of an ongoing project to implement [MKW-SP Matchmaking](https://docs.google.com/document/d/12nnnkNtp28ovD2e4XNroavy8nKg_f5jByOizTJSU0UQ/edit) and is not representative of the final result.

2023-01-30 23:56 UTC, vabold commented on payload/game/ui/MatchmakingPage.cc
> +bool MatchmakingPage::read(std::optional<STCMessage> &event) {
Unnecessary whitespace.

2023-01-31 00:15 UTC, vabold requested changes
Files should be run through clang-format.

I'm not qualified enough to review the Rust side of things.

2023-01-31 00:15 UTC, vabold commented on payload/game/ui/FriendMatchingPage.cc
> +    SP_LOG("FriendMatchingPage::onRefocus");
Remove debug log.

2023-01-31 00:15 UTC, vabold commented on payload/game/ui/FriendMatchingPage.cc
> +    SP_LOG("FriendMatchingPage::prepareStartClient");
Same as above.

2023-01-31 00:15 UTC, vabold commented on payload/game/ui/MatchmakingPage.hh
> +class MatchmakingPage : public Page {
The class should be called `RandomMatchingPage` to pair with `FriendMatchingPage`.

2023-01-31 00:15 UTC, vabold commented on payload/game/ui/MatchmakingPage.hh
> +#include <protobuf/Matchmaking.pb.h>
https://github.com/stblr/mkw-sp/issues/245

2023-01-31 00:15 UTC, vabold commented on payload/game/ui/PageId.hh
> +    MatchmakingConnect = 0x6F,
Replace the unused page at 0x8F instead (originally `RandomMatchingPage`).

2023-01-31 00:15 UTC, vabold commented on payload/game/ui/MatchmakingPage.hh
> +}
Namespace comment (incredibly useful feedback, I know!).

2023-01-31 00:15 UTC, vabold commented on payload/game/ui/Section.cc
> +        return new MatchmakingPage;
These are done based on page ID order, not alphabetical order.

2023-01-31 00:15 UTC, vabold commented on payload/sp/cs/RoomClient.cc
> +    m_login_info = login_info;
In C++ we use camelCase, not snake_case.

2023-01-31 00:15 UTC, vabold commented on payload/sp/cs/RoomClient.cc
> +    SP_LOG("RoomClient::resolve(m_state: %d)", m_state);
Remove debug log.

2023-01-31 20:40 UTC, stblr requested changes
Review done for the C++ part. For the Rust part, could you please first add it to the CI?

2023-01-31 20:40 UTC, stblr commented on configure.py
> +    command = f'{sys.executable} $nanopb $in -I protobuf -L "#include <vendor/nanopb/%s>" -D build/protobuf -q',
What does this do?

2023-01-31 20:40 UTC, stblr commented on configure.py
> +        os.path.join('payload', 'game', 'ui', 'RandomMatchingPage.cc'),
Alphasort

2023-01-31 20:40 UTC, stblr commented on payload/game/ui/Section.cc
> +#include "game/ui/RandomMatchingPage.hh"
Alphasort

2023-01-31 22:33 UTC, GnomedDev commented on configure.py
> +    command = f'{sys.executable} $nanopb $in -I protobuf -L "#include <vendor/nanopb/%s>" -D build/protobuf -q',
This allows for `import` statements to be used in `.proto` files, as otherwise nanopb looks for the imports in the wrong folder. I needed it for `Login.proto`.

2023-02-01 22:37 UTC, stblr commented on tools/matchmaking/docker-compose.yml
> +            POSTGRES_DATABASE: matchmaking
Did you consider an in-app database like sqlite?

2023-02-01 22:37 UTC, stblr commented on tools/matchmaking/src/main.rs
> +    gameservers: Arc<DashMap<GameserverID, Gameserver>>,
Are you aware of the caveats of `DashMap` with `async`/`await`? https://draft.ryhl.io/blog/shared-mutable-state/

2023-02-01 22:37 UTC, stblr commented on tools/matchmaking/src/main.rs
> +                if room.is_battle == is_battle && room.clients.len() < 12 {
Is the idea for battle rooms to randomly switch between modes (I don't play battle)?

2023-02-01 22:37 UTC, stblr commented on tools/matchmaking/src/main.rs
> +                _ => todo!(),
This allows the client to crash the whole process, right?

2023-02-01 22:37 UTC, stblr commented on tools/matchmaking/src/main.rs
> +        ws_forward::WebsocketListener::new("127.0.0.1:20037", server.clone()).await?;
How were the port numbers chosen?

2023-02-01 22:37 UTC, stblr commented on tools/matchmaking/src/main.rs
> +                _ => todo!(),
Same

2023-02-01 22:57 UTC, Zachruff commented on tools/matchmaking/src/main.rs
> +                if room.is_battle == is_battle && room.clients.len() < 12 {
In vanilla since there are only two modes battle worldwides just alternate back and forth between the two. MK8DX which has 5 modes yes it cycles through all of them.

2023-02-01 23:22 UTC, GnomedDev commented on tools/matchmaking/src/main.rs
> +        ws_forward::WebsocketListener::new("127.0.0.1:20037", server.clone()).await?;
20036 was randomly chosen, and I picked the number after aswell. They don't seem to be used anywhere.

2023-02-01 23:25 UTC, GnomedDev commented on tools/matchmaking/src/main.rs
> +    gameservers: Arc<DashMap<GameserverID, Gameserver>>,
Yes, I use it in multiple projects and serenity-rs (async discord bot library) uses it significantly. I could make a wrapper that returned always non-send refs if you want?

2023-02-01 23:28 UTC, GnomedDev commented on tools/matchmaking/docker-compose.yml
> +            POSTGRES_DATABASE: matchmaking
I did, I chose against it because:
- Performance, postgres is faster
- Scalability, database can run on different hardware if it becomes a scaling concern
- Type safety, sqlite stores everything as strings and will implicitly cast in bad ways
- I have only ever used postgres for a serious project

2023-02-01 23:29 UTC, GnomedDev commented on tools/matchmaking/src/main.rs
> +                if room.is_battle == is_battle && room.clients.len() < 12 {
I hadn't thought that far ahead, but alternating or voting on modes are indeed ideas for the future.

2023-02-01 23:31 UTC, GnomedDev commented on tools/matchmaking/src/main.rs
> +                _ => todo!(),
Yes, this should not be deployed as is, this is just an initial implementation to allow for others to build on (for example: UI, crypto, etc).

2023-02-02 20:13 UTC, stblr commented on tools/matchmaking/src/main.rs
> +        ws_forward::WebsocketListener::new("127.0.0.1:20037", server.clone()).await?;
For the other services, 21328 (0xSP) and following ports were used.

2023-02-02 20:21 UTC, stblr commented on tools/matchmaking/src/main.rs
> +    gameservers: Arc<DashMap<GameserverID, Gameserver>>,
Maybe, but not in this PR. Message passing should also be considered.

2023-02-02 20:21 UTC, stblr commented on tools/matchmaking/docker-compose.yml
> +            POSTGRES_DATABASE: matchmaking
Are there instructions somewhere to launch the db?

2023-02-02 20:53 UTC, GnomedDev commented on tools/matchmaking/docker-compose.yml
> +            POSTGRES_DATABASE: matchmaking
`docker-compose up -d`

2023-02-02 21:27 UTC, GnomedDev commented on tools/matchmaking/src/main.rs
> +        ws_forward::WebsocketListener::new("127.0.0.1:20037", server.clone()).await?;
What ports should I use then? also this feels real bikesheddy lol

2023-02-02 21:28 UTC, vabold commented on tools/matchmaking/src/main.rs
> +        ws_forward::WebsocketListener::new("127.0.0.1:20037", server.clone()).await?;
Bikesheddy? Come on now, this project is at least garage-level.

2023-02-02 21:31 UTC, stblr commented on tools/matchmaking/src/main.rs
> +        ws_forward::WebsocketListener::new("127.0.0.1:20037", server.clone()).await?;
21331 21332

2023-02-02 21:58 UTC, stblr approved these changes

2023-02-02 21:58 UTC, merged