Online race rework
stblr/mkw-sp pull request #567
Opened 2023-02-04 16:47 UTC by stblr

2023-02-05 17:56 UTC, GnomedDev requested changes
Looks good, just some small concerns.

`.ok_or(anyhow!("whatever"))` should also be replaced with `.context("whatever")`, wherever it is used.

2023-02-05 17:56 UTC, GnomedDev commented on tools/gameserver/Cargo.toml
> +dlv-list = "0.5.0"
What's the reason for swapping slab out for this?

2023-02-05 17:56 UTC, GnomedDev commented on tools/gameserver/src/room.rs
> +                else => return Ok(None),
```suggestion
                _ => return Ok(None),
```

2023-02-05 17:56 UTC, GnomedDev commented on tools/gameserver/src/room.rs
> +            tracing::info!("{:?} {:?}", client_index, race);
Info is for useful but not important logs, this should be `debug`

2023-02-05 17:56 UTC, GnomedDev commented on tools/gameserver/src/room.rs
> +            tracing::info!("{:?}", server_frame);
Same with above.

2023-02-05 17:56 UTC, GnomedDev commented on tools/gameserver/src/room.rs
> +        let task = tokio::spawn(async move {
This should be moved to it's own function, avoid having to spawn an empty task just to replace it.

2023-02-05 17:56 UTC, GnomedDev commented on tools/gameserver/src/unreliable_socket.rs
> +        let mut tmp = [0u8; 1024]; // TODO make that configurable
```suggestion
        let mut buf = [0u8; 1024]; // TODO make that configurable
```

2023-02-05 17:56 UTC, GnomedDev commented on tools/netprotocol/src/async_stream.rs
> +        assert!(*self.size == 0);
This check could be made mandatory by using an `Option<NonZeroUsize>`

2023-02-05 21:26 UTC, stblr commented on tools/gameserver/Cargo.toml
> +dlv-list = "0.5.0"
This was used for iteration in one of the prototypes but it looks like this is not needed anymore. Will swap it back because there is no convenient way to get the key before constructing the value.

2023-02-05 21:31 UTC, stblr commented on tools/netprotocol/src/async_stream.rs
> +        assert!(*self.size == 0);
I will see if there is a way to implement the checks at compile time (have `start_write` return a struct with a mutable reference).

2023-02-05 21:32 UTC, stblr commented on tools/gameserver/src/room.rs
> +                else => return Ok(None),
That syntax doesn't look to be legal.

2023-02-05 21:38 UTC, GnomedDev commented on tools/gameserver/src/room.rs
> +                else => return Ok(None),
Oh, huh, didn't actually know `tokio::select!` had that `else` syntax.

2023-02-06 20:35 UTC, stblr commented on tools/gameserver/Cargo.toml
> +dlv-list = "0.5.0"
Went back with slab, will see if I can implement faster iteration and submit it upstream, or if I'm missing something.

2023-02-06 20:35 UTC, stblr commented on tools/gameserver/src/unreliable_socket.rs
> +        let mut tmp = [0u8; 1024]; // TODO make that configurable
Renamed it to `message` like in `AsyncStream`.

2023-02-06 20:36 UTC, stblr commented on tools/netprotocol/src/async_stream.rs
> +        assert!(*self.size == 0);
Dropped cancel safety for writes as well as split reader/writer, as this is no longer needed.

2023-02-06 21:10 UTC, merged