Cleanup configure.py
stblr/mkw-sp pull request #594
Opened 2023-02-15 20:31 UTC by GnomedDev

- Uses built-in `glob` module to prevent having to list every file manually
- Properly checks for `os.environ.get` returning `None` or `""
- Sorts imports according to default VScode behaviour (and removes unused `subprocess` import)
- Avoids pylance getting confused by removing use of `target` after the for loop defining it.

2023-02-20 03:33 UTC, riidefi commented
This should simplify things. Though with the globs, we shouldn't include the files in the `Emulator` file in actual builds. Implementing a few APIs, they allow some SP classes to run sans-modification on PC targets. We might want to simply remove them altogether.

2023-02-23 18:55 UTC, stblr requested changes
The README should be updated to tell users to run `configure.py` every time a file is added or removed.

2023-02-24 19:46 UTC, stblr commented
Should we wait for a PyPy release that supports 3.10? PyPy is still recommended in the README, but the gains are likely more limited now with the move to LZMA.

2023-02-24 20:31 UTC, GnomedDev commented
`configure.py` doesn't even take that long, and seeing that we are running lots of small scripts I can imagine pypy isn't helping that much (no time for JIT to warm up, might even be slower thinking about it)

2023-03-04 10:21 UTC, stblr requested changes
PyPy should no longer be mentioned in the README.

2023-03-04 10:21 UTC, stblr commented on README.md
> +added to the project, and can be skipped if only recompiling with changed files.
Or removed.

2023-03-04 14:42 UTC, stblr approved these changes

2023-03-04 14:42 UTC, merged

2023-03-06 06:36 UTC, riidefi commented
This breaks Windows builds

2023-03-06 06:48 UTC, vabold commented
inb4 "good"