Implement MVP Online UI
stblr/mkw-sp pull request #596
Opened 2023-02-18 16:56 UTC by GnomedDev

This PR implements the minimum viable product for online/matchmaking UI.

A couple of things to take note of:
- `OnlineConnectionManagerPage` transitions away to an error as soon as it fails to connect, meaning direct connection cannot be used without working matchmaking servers, this should be fixed before release
-  `OnlineConnectionManagerPage` has to override `dt` for the `AsyncSocket` to be correctly destroyed, this should be looked on a larger scale (are we leaking memory due to most page destructors not being called?)
- `OnlineTopPage` hasn't implemented the friends page or track packs, and currently the buttons do nothing
- `OnlineModeSelectPage` only shows 5000VR, which is probably a fallback default, I'll look into where that is set soon
- `RandomMatchingPage`'s current `RoomClient` handler may mean that the first member of a Room could send settings and have the Room respect it?

2023-02-21 17:17 UTC, stblr requested changes

2023-02-21 17:17 UTC, stblr commented on payload/game/ui/FriendButton.hh
> +    void load(const char** animInfo, const char* dir, const char* file, const char* variant, bool r8, bool pointerOnly);
What about the other member functions?

2023-02-21 17:17 UTC, stblr commented on configure.py
> +        os.path.join('payload', 'game', 'ui', 'OnlineConnectionManagerPage.cc'),
Ordering

2023-02-21 17:17 UTC, stblr commented on tools/gameserver/src/room.rs
> +                        Err(err) => tracing::error!("Failed to handle select request: {err}"),
The TODO comment can be kept.

2023-02-21 17:17 UTC, stblr commented on payload/sp/cs/RoomClient.cc
>  }
I would rather suggest to add a callback to the handler to prevent frontend details from leaking into the backend.

2023-02-21 17:17 UTC, stblr commented on payload/game/ui/OnlineConnectionManagerPage.cc
> +}
The base class already does this AFAIK.

2023-02-21 17:17 UTC, stblr commented on payload/game/ui/OnlineTopPage.cc
> +        m_pageTitleText.setMessage(0x7f1);
Decimal

2023-02-21 17:17 UTC, stblr commented on payload/game/ui/OnlineTopPage.cc
> +        m_pageTitleText.setMessage(0x7f2);
Same

2023-02-21 17:19 UTC, GnomedDev commented on payload/game/ui/OnlineConnectionManagerPage.cc
> +}
The base class's implementation does not end up calling the `AsyncSocket` destructor and therefore caused "Client already logged in" issues as mentioned in the PR description.

2023-02-21 17:22 UTC, GnomedDev commented on payload/game/ui/FriendButton.hh
> +    void load(const char** animInfo, const char* dir, const char* file, const char* variant, bool r8, bool pointerOnly);
What do you mean? I implemented the bare minimum to get the button to load, as this is a MVP and other FriendButton stuff can be implemented later.

2023-02-21 17:25 UTC, stblr commented on payload/game/ui/FriendButton.hh
> +    void load(const char** animInfo, const char* dir, const char* file, const char* variant, bool r8, bool pointerOnly);
The `FriendButton` vfuncs won't be called so this is just a regular `PushButton`.

2023-02-21 17:28 UTC, GnomedDev commented on payload/game/ui/FriendButton.hh
> +    void load(const char** animInfo, const char* dir, const char* file, const char* variant, bool r8, bool pointerOnly);
Honestly probably for the best, a lot of the friend code is directly calling gamespy stuff (hence the `WifiFriendMenu` being deleted and the button being stubbed), the only reason this I even call to this load function is to avoid a broken animation.

2023-02-21 17:46 UTC, stblr commented on payload/game/ui/FriendButton.hh
> +    void load(const char** animInfo, const char* dir, const char* file, const char* variant, bool r8, bool pointerOnly);
Since this is temporary and doesn't break anything, I guess this is fine to have this hybrid class for now.

2023-02-21 17:56 UTC, GnomedDev commented on payload/sp/cs/RoomClient.cc
>  }
Wouldn't that remove the ability to report `30004` (`RoomClient` missing), as a RoomClient would have to be there to call the handler and calling a method with a null `this` pointer is UB.

2023-02-24 19:43 UTC, stblr commented on payload/game/ui/OnlineModeSelectPage.cc
> +    m_raceButton.setMessage("go", 0x106a, &info);
Decimal

2023-02-24 19:43 UTC, stblr commented on payload/game/ui/OnlineModeSelectPage.cc
> +    m_battleButton.setMessage("go", 0x106b, &info);
Same

2023-02-24 19:43 UTC, stblr commented on payload/game/ui/RandomMatchingPage.cc
> +        m_title.setMessage(0xfa0);
Decimal

2023-02-24 19:43 UTC, stblr commented on payload/game/ui/OnlineModeSelectPage.cc
> +        m_titleText.setMessage(0xfa0);
Decimal

2023-02-24 19:43 UTC, stblr commented on payload/game/ui/OnlineTopPage.cc
> +    m_instructionText.setMessage(0x10d6 + button->m_index);
Decimal

2023-02-24 19:43 UTC, stblr commented on payload/game/ui/OnlineConnectionManagerPage.cc
> +}
We should at least open an issue to investigate this.

2023-02-24 19:43 UTC, stblr commented on payload/sp/cs/RoomClient.cc
>  }
You could make this a method of e.g. `SectionManager` or `GlobalContext` that would be called by the callback but also when `RoomClient` is missing.

2023-02-25 14:52 UTC, stblr approved these changes

2023-02-25 14:53 UTC, merged