Remove Page ASM patches
stblr/mkw-sp pull request #598
Opened 2023-02-19 23:10 UTC by GnomedDev

2023-02-20 03:29 UTC, riidefi commented on payload/game/ui/AwardPage.cc
> +        panic("Unknown section 0x%X, please report to MKW-SP devs!", static_cast<s32>(currentSectionId));
What's the game's behavior here?

2023-02-20 13:23 UTC, GnomedDev commented on payload/game/ui/AwardPage.cc
> +        panic("Unknown section 0x%X, please report to MKW-SP devs!", static_cast<s32>(currentSectionId));
Stock treats sections it doesn't know about as VS (stock logic is a bit reordered and more repetitive). This should only possibly be hit for 0x37 which is marked as unknown and we do not transition to.

2023-03-07 21:49 UTC, GnomedDev commented
This is okay to merge without, until the format the world PR is merged.

2023-03-17 18:57 UTC, stblr requested changes

2023-03-17 18:57 UTC, stblr commented on payload/game/ui/page/DemoPage.hh
> +    REPLACE void onInit() override;
public

2023-03-17 18:57 UTC, stblr commented on payload/game/ui/TitlePage.hh
> +    REPLACE void onActivate() override;
public

2023-03-17 18:57 UTC, stblr commented on payload/game/ui/page/DemoPage.cc
> +
Please use `LayoutUIControl::load`.

2023-03-17 18:57 UTC, stblr commented on payload/game/ui/ControlLoader.hh
Can be axed.

2023-03-17 19:04 UTC, stblr commented on payload/game/ui/ControlLoader.hh
Or be used to implement `LayoutUIControl::load` in C++.

2023-03-17 19:35 UTC, GnomedDev commented on payload/game/ui/page/DemoPage.cc
> +
Huh, I don't see that in the original game, was it inlined or is it an SP thing?

2023-03-17 19:35 UTC, stblr commented on payload/game/ui/page/DemoPage.cc
> +
Inlined.

2023-03-17 19:36 UTC, stblr commented on payload/game/ui/page/DemoPage.cc
> +
https://github.com/stblr/mkw-sp/blob/4aaf4b0b374658f4eaeabe31b57a97d567188523/payload/game/ui/UIControl.c#L14

2023-03-17 19:37 UTC, GnomedDev commented on payload/game/ui/page/DemoPage.cc
> +
Okay, that's going to be my next target for cleanup, for sure.

2023-03-21 19:55 UTC, stblr approved these changes

2023-03-21 19:56 UTC, merged