Add basic save state system
stblr/mkw-sp pull request #604
Opened 2023-02-25 13:41 UTC by GnomedDev

Allows users (or the mod, for a future practice mode) to save the state of a kart and restore it later, without needing heavy dolphin savestates. This technically saves a lot more than necessary, as I went through trying to find what would stop desyncs, but the headers could be useful for future use.

`KartSaveState` is currently sized at `4560` (`0x11d0`), so it isn't a massive memory hog.

This could be bound to a button, which I may do in this PR or a future PR depending on how long it takes to merge, but is currently bound to the `/store` and `/reload` commands.

2023-02-25 15:10 UTC, stblr requested changes

2023-02-25 15:10 UTC, stblr commented on configure.py
> +        os.path.join('payload', 'game', 'kart', 'KartSaveState.cc'),
Ordering

2023-02-25 15:10 UTC, stblr commented on payload/egg/core/eggSystem.cc
> +#include <game/kart/KartObjectManager.hh>
Ordering

2023-02-25 15:10 UTC, stblr commented on payload/game/kart/KartSettings.hh
> +    u16 wheelCount1; // Used for intiialising tires
Could just be renamed to `susCount` and `tireCount`.

2023-02-25 15:10 UTC, stblr commented on payload/game/kart/KartObjectProxy.hh
> +class PlayerModel;
Ordering

2023-02-25 15:10 UTC, stblr commented on payload/game/ui/page/RacePage.cc
> +
Does this really belong here?

2023-02-25 15:10 UTC, stblr commented on payload/game/kart/KartSettings.hh
> +
No need for a newline.

2023-02-25 15:10 UTC, stblr commented on payload/game/kart/KartSus.hh
> +};
Is this an actual thing?

2023-02-25 15:50 UTC, GnomedDev commented on payload/game/kart/KartSus.hh
> +};
Ah, this was KartPart in ghidra, I misread it.

2023-02-25 16:52 UTC, GnomedDev commented on payload/game/ui/page/RacePage.cc
> +
It was the first place I could think of that I could use the heap and is loaded only during the race, where else do you suggest?

2023-02-26 11:53 UTC, stblr commented on payload/game/ui/page/RacePage.cc
> +
`KartObjectManager::CreateInstance`, the only issue is that we are already replacing this function from C code.

2023-02-26 11:55 UTC, stblr commented on payload/sp/SaveStateManager.cc
> +    m_kartSaveState = new Kart::KartSaveState;
This leaks memory.

2023-02-26 13:11 UTC, stblr commented on payload/sp/SaveStateManager.cc
> +    m_kartSaveState = new Kart::KartSaveState;
By the way, do we even need a separate allocation?

2023-02-26 15:09 UTC, GnomedDev commented on payload/sp/SaveStateManager.cc
> +    m_kartSaveState = new Kart::KartSaveState;
Thinking about it, probably not, I implemented this way to lazy allocate the save state but that doesn't seem possible or useful (see dev chat last night).

2023-02-27 19:33 UTC, stblr approved these changes

2023-02-27 19:33 UTC, merged