Rewrite exception callback in C++
stblr/mkw-sp pull request #609
Opened 2023-02-27 21:35 UTC by vabold

Notably, this removes the automated scrolling and adds diagonal inputs.

2023-02-28 05:27 UTC, vabold commented
With added GC and classic controller support, this should be good for review.

2023-02-28 21:25 UTC, stblr requested changes

2023-02-28 21:25 UTC, stblr commented on payload/egg/util/eggException.cc
> +}
```suggestion
#include "egg/core/eggThread.hh"

#include <common/Clock.hh>
extern "C" {
#include <revolution/kpad.h>
#include <revolution/os.h>
#include <revolution/pad.h>
#include <revolution/vi.h>
}
```

2023-02-28 21:25 UTC, stblr commented on payload/egg/util/eggException.cc
> +    u32 input;
No reason to create these variables so early, as they are not used in the outer scope.

2023-02-28 21:25 UTC, stblr commented on payload/egg/util/eggException.cc
> +        input = wStatus.buttons & 15;
In my opinion this is a bit cryptic, I would suggest to have one boolean per direction.

2023-02-28 21:25 UTC, stblr commented on payload/revolution/os.h
> +extern BOOL OSRestoreInterrupts(BOOL);
```suggestion
BOOL OSDisableInterrupts(void);
BOOL OSEnableInterrupts();
BOOL OSRestoreInterrupts(BOOL);
```

2023-03-03 19:55 UTC, vabold commented on payload/egg/util/eggException.cc
> +}
Applied, though there is a new include to review.

2023-03-03 19:55 UTC, vabold commented on payload/egg/util/eggException.cc
> +    u32 input;
Fixed.

2023-03-03 19:55 UTC, vabold commented on payload/revolution/os.h
> +extern BOOL OSRestoreInterrupts(BOOL);
Applied.

2023-03-03 19:55 UTC, vabold commented on payload/egg/util/eggException.cc
> +        input = wStatus.buttons & 15;
Fixed.

2023-03-03 19:59 UTC, stblr requested changes

2023-03-03 19:59 UTC, stblr commented on payload/egg/util/eggException.hh
> +static constexpr bool CheckCLStickThreshold(s16 stick);
```suggestion
```

2023-03-03 19:59 UTC, stblr commented on payload/egg/util/eggException.cc
> +        WPADCLStatus clStatus;
```suggestion
        KPADStatus wStatus{};
        PADStatus gcStatus[4]{};
        WPADCLStatus clStatus{};
```

2023-03-03 20:21 UTC, vabold commented on payload/egg/util/eggException.hh
> +static constexpr bool CheckCLStickThreshold(s16 stick);
Applied.

2023-03-03 20:22 UTC, vabold commented on payload/egg/util/eggException.cc
> +        WPADCLStatus clStatus;
Applied.

2023-03-03 20:26 UTC, stblr approved these changes

2023-03-03 20:29 UTC, merged