Random Team size
stblr/mkw-sp pull request #616
Opened 2023-03-06 13:42 UTC by Unnamed8932

2023-03-06 17:50 UTC, GnomedDev requested changes
This should also extract the random selection to a function somewhere, rebasing to fix the commit names would also be a good idea.

2023-03-06 17:50 UTC, GnomedDev commented on payload/game/ui/SingleTopPage.cc
> +#include "vendor/libhydrogen/hydrogen.h"
```suggestion

extern "C" {
#include <vendor/libhydrogen/hydrogen.h>
}
```

2023-03-06 18:55 UTC, Unnamed8932 commented
Ok, I will update. Should I do the same change with MultiTopPage.cc ?

2023-03-06 19:04 UTC, stblr commented
> Ok, I will update. Should I do the same change with MultiTopPage.cc ?

Yes.

2023-03-06 19:04 UTC, stblr commented
LGTM if @GnomedDev's comments are addressed.

2023-03-07 09:11 UTC, Unnamed8932 commented
Should I also update the commit names?

2023-03-07 09:22 UTC, stblr commented
The commits can all be squashed I think.

2023-03-07 09:29 UTC, riidefi commented on payload/game/ui/SingleTopPage.cc
> +    }
Can we pull this out into its own function rather than having 4 copies of it?

2023-03-07 09:33 UTC, Unnamed8932 commented
Good question, yes of course that would be better. But where should I write this function?

2023-03-07 09:39 UTC, riidefi commented
Maybe in `SP::ClientSettings` as a standalone function

2023-03-07 09:48 UTC, Unnamed8932 commented
So in ClientSettings.cc ?

2023-03-07 09:52 UTC, riidefi commented
Sure. Also it'd probably be best to clear in the name that this function is not "pure" and may generate a random number.

2023-03-13 09:19 UTC, Unnamed1242 commented
Ok, I have made the changes and it does compile. I hope it is ok like this :)

2023-03-13 16:33 UTC, GnomedDev requested changes
Please also squash these commits with a rebase, if possible.

Sorry for being a bit nit picky, the logic generally LGTM.

2023-03-13 16:33 UTC, GnomedDev commented on payload/game/ui/SingleTopPage.cc
> +}
```suggestion
#include <sp/settings/ClientSettings.hh>
extern "C" {
#include <vendor/libhydrogen/hydrogen.h>
}
```

2023-03-13 16:33 UTC, GnomedDev commented on payload/sp/settings/ClientSettings.cc
> +u32 maxTeamSize;
```suggestion
u32 getMaxTeamSize(u32 teamsizeSetting) {
    u32 maxTeamSize;
```

2023-03-13 16:33 UTC, GnomedDev commented on payload/sp/settings/ClientSettings.hh
>  #include "sp/settings/Settings.hh"
```suggestion
#include "sp/settings/Settings.hh"

#include <game/util/Registry.hh>
extern "C" {
#include <vendor/libhydrogen/hydrogen.h>
}
```

2023-03-13 16:33 UTC, GnomedDev commented on assets/message/MenuSP_U.bmg.json5
> +}
Unnecessary diff?

2023-03-14 11:31 UTC, Unnamed1242 commented
"Sorry for being a bit nit picky" No it is ok, after all, you want it to be neat and tidy. "the logic generally LGTM" Thank you. I love to write such logic codes.

2023-03-14 11:43 UTC, Unnamed1242 commented
For the "MenuSP_U.bmg.json5" File I removed this brace accidently and wrote it back, I don't know why it is declared as change, though I have made no changes there.

2023-03-14 15:04 UTC, riidefi commented on payload/sp/settings/ClientSettings.cc
> +u32 getmaxTeamSize(u32 teamsizesetting) {
I would much rather you take in a `TeamSize` enum rather than a `u32`. Also I believe we use camelCase, so `getMaxTeamSize` would be the name, as "team size" is a set of two distinct English words. And not to be too pedantic, but usually for static functions (not members of a class), we capitalize the first letter (so, "GetMaxTeamSize").
I would additionally prefer something like "Generate" over "Get" to make it clear that this function may return a randomized output and cannot be cached from race-to-race.

2023-03-14 15:14 UTC, Unnamed1242 commented
"So Unix files should have an empty line at the end, which yours appears to be missing (hence the red circle). Just adding a blank line should fix." Oh ok, I didn't see lol. And GenerateMaxTeamSize would be a better name indeed.

2023-03-15 10:33 UTC, Unnamed1242 commented
I have updated the name of the function now. But I can't get the red circle away. It still says there is no newline at the end of file.

2023-03-15 11:33 UTC, Unnamed1242 commented
Thank you for your patience :) , I think it is all fixed now. If all is ok, I will squash the commits on Friday.

2023-03-15 21:49 UTC, stblr approved these changes

2023-03-15 21:50 UTC, merged