Implement basic Track Pack System
stblr/mkw-sp pull request #655
Opened 2023-04-01 09:28 UTC by GnomedDev

Draft as unfinished and based on course cache PR.

2023-04-03 06:56 UTC, riidefi commented on payload/egg/core/eggTaskThread.hh
> +    void request(TFunction mainFunction, T arg, void *taskEndMessage);
This change doesn't make any sense. Taking an arbitrary `void*` as user data is standard practice in C code. `TaskThread` isn't valid for any arbitrary type of `arg`. If you want a safe interface, make a wrapper type or freestanding function.

2023-04-03 07:02 UTC, riidefi commented on payload/sp/TrackPackManager.cc
> +        panic("Failed to parse integer!");
Ideally we wouldn't crash from an invalid .ini file. Not a blocker but perhaps we could adapt this function to return `std::expected<u32, FixedString<32>>` or such?

2023-04-03 07:03 UTC, riidefi commented on payload/sp/TrackPackManager.cc
> +    while (auto property = iniReader.next()) {
auto [section, key] = iniReader.next()

2023-04-03 07:05 UTC, riidefi commented on payload/sp/TrackPackManager.cc
> +    if (gameMode == 1 || gameMode == 2) {
Do we not have an enum for this?

2023-04-03 07:06 UTC, riidefi commented on payload/sp/vanillaTracks.hh
> +const std::string_view vanillaManifest = R"(
I believe this is invalid if included in multiple files. You can fix that by making it `constexpr`, which may also allow for some additional optimization.

2023-04-03 09:38 UTC, GnomedDev commented on payload/sp/TrackPackManager.cc
> +        panic("Failed to parse integer!");
What would the user facing behavior you would like to see? If one of the pack files is invalid for now, and we didn't panic, it would need some UI code to implement a dialog or something, which should probably be done in a follow up PR.

2023-04-03 09:38 UTC, GnomedDev commented on payload/egg/core/eggTaskThread.hh
> +    void request(TFunction mainFunction, T arg, void *taskEndMessage);
Ah yes, I did this while debugging issues and never reverted it, I'll revert now.

2023-04-03 09:42 UTC, riidefi commented on payload/sp/vanillaTracks.hh
> +const std::string_view vanillaManifest = R"(
If you are not allowed to `#include` the file, then it is not a header.

2023-04-03 09:44 UTC, GnomedDev commented on payload/sp/vanillaTracks.hh
> +const std::string_view vanillaManifest = R"(
It shouldn't be a header anyway, this is just making up for the fact C++ doesn't have a form of include_str.

2023-04-03 15:03 UTC, GnomedDev commented on payload/sp/TrackPackManager.cc
> +    while (auto property = iniReader.next()) {
This doesn't seem to compile?

2023-04-04 03:37 UTC, riidefi commented on payload/sp/TrackPackManager.cc
> +    while (auto property = iniReader.next()) {
`*property`*

2023-04-04 03:39 UTC, riidefi commented on payload/sp/vanillaTracks.hh
> +const std::string_view vanillaManifest = R"(
Probably better to make it either `constexpr` or `inline` so it's a valid header for now. If we want to avoid duplicate bodies being generated we can put it in its own .cc file later, but I think the linker will merge them anyway since it's const.

2023-04-04 03:40 UTC, riidefi commented on payload/sp/TrackPackManager.cc
> +        panic("Failed to parse integer!");
Fair

2023-04-04 03:43 UTC, riidefi commented on payload/sp/FixedString.hh
> +        auto written = Util_toUtf16(m_buf.data(), m_buf.size(), view.data(), view.size());
m_len = ...

2023-04-05 01:14 UTC, riidefi requested changes

2023-04-05 01:14 UTC, riidefi commented on payload/game/ui/GhostManagerPage.cc
> +        };
Stray semicolons?

2023-04-05 01:14 UTC, riidefi commented on payload/game/ui/Section.cc
> +    SP_LOG("addPage 0x%x", pageId);
Print both hex & decimal ideally

2023-04-05 01:14 UTC, riidefi commented on payload/game/ui/Section.cc
> +    SP_LOG("addActivePage 0x%x", pageId);
Ditto

2023-04-05 01:14 UTC, riidefi commented on payload/sp/FixedString.hh
> +
Optional: Add constructor from std::wstring_view and conversion to std::wstring_view (to match API of FixedString)

2023-04-05 01:14 UTC, riidefi commented on payload/sp/ShaUtil.cc
> +std::array<char, 0x28 + 1> sha1ToHex(const Sha1 &sha1) {
Probably better to return a FixedString here?

2023-04-05 01:14 UTC, riidefi commented on payload/sp/TrackPackManager.cc
> +std::expected<Sha1, const char *> sha1FromSv(std::string_view sv) {
Move to ShaUtil?

2023-04-05 01:14 UTC, riidefi commented on payload/sp/TrackPackManager.cc
> +            auto trackId = sha1FromSv(sv);
TRY should clean this up a bit

2023-04-05 01:14 UTC, riidefi commented on payload/sp/TrackPackManager.cc
> +    assert(m_parseError == nullptr);
See this is why I'm not a huge fan of constructors in C++ turning every type into an optional type.

2023-04-05 11:35 UTC, GnomedDev commented on payload/sp/ShaUtil.cc
> +std::array<char, 0x28 + 1> sha1ToHex(const Sha1 &sha1) {
Doesn't FixedString have capacity and length? Because it will always be the same amount of chars, this is simpler imo.

2023-04-06 01:50 UTC, riidefi requested changes

2023-04-06 01:50 UTC, riidefi commented on payload/sp/TrackPackManager.cc
> +            std::string_view sv(buf, position);
`std::string_view` need not be null-terminated, so we should be able to avoid a temporary buffer (like `buf`) entirely.

2023-04-06 01:50 UTC, riidefi commented on payload/sp/TrackPackManager.cc
> +            if (m_unreleasedTracks.size() == 0 || m_unreleasedTracks.back().sha1 != sha1) {
Usually more idiomatic to use `.empty()` instead of `.size() == 0`

2023-04-06 01:50 UTC, riidefi commented on payload/sp/TrackPackManager.cc
> +        if (m_trackDb.size() == 0 || m_trackDb.back().sha1 != *sha1) {
ditto

2023-04-06 01:50 UTC, riidefi commented on payload/sp/TrackPackManager.cc
> +    auto raceConfig = System::RaceConfig::Instance();
auto*

2023-04-06 01:50 UTC, riidefi commented on payload/sp/TrackPackManager.hh
> +    WFixedString<64> name = {};
Probably makes sense to put `name` last for cache reasons?

2023-04-06 01:50 UTC, riidefi commented on payload/sp/TrackPackManager.hh
> +    static WFixedString<64> s_name;
std::unique_ptr<WFixedString<64>> maybe?

2023-04-06 01:50 UTC, riidefi commented on payload/sp/ShaUtil.cc
> +        sprintf(hex.data() + (i * 2), "%02x", (*(data + i)) & 0xff);
Can you adapt to use `snprintf`? Wouldn't mind completely blacklisting this function

2023-04-06 01:54 UTC, riidefi commented on payload/sp/ShaUtil.cc
> +std::array<char, 0x28 + 1> sha1ToHex(const Sha1 &sha1) {
That's true but it seems unintuitive to see `.data()` be valid for a cstr later. If this isn't performance critical, it'd probably be a lot more clear to suffer the 4 byte penalty and use a `FixedString`.

2023-04-06 02:10 UTC, riidefi commented on payload/sp/TrackPackManager.cc
> +    for (const auto &track : m_unreleasedTracks) {
If you `std::sort` this array earlier, you can use `std::lower_bound` to perform a binary search

2023-04-06 02:10 UTC, riidefi commented on payload/sp/TrackPackManager.cc
> +    for (const auto &track : m_unreleasedTracks) {
(optional)

2023-04-06 02:18 UTC, riidefi commented on payload/sp/TrackPackManager.cc
> +    for (const auto &track : m_unreleasedTracks) {
Probably just slower here since you reload the ini files every race (?)

2023-04-06 12:38 UTC, GnomedDev commented on payload/sp/TrackPackManager.cc
> +    for (const auto &track : m_unreleasedTracks) {
I reload every time the pack selection page is initialised, or every race when capturing thumbnails

2023-04-06 14:23 UTC, GnomedDev commented on payload/sp/TrackPackManager.hh
> +    static WFixedString<64> s_name;
Wouldn't `unique_ptr` heap allocate the `WFixedString`? That wouldn't work as we need to keep all this data across the scene boundary (heap cleared).

2023-04-06 17:31 UTC, riidefi commented on payload/sp/TrackPackManager.hh
> +    static WFixedString<64> s_name;
I suppose you could allocate in the System heap. It is probably better to just extend the structure and place TrackPackManager at the end (allocate more memory).

2023-04-06 17:36 UTC, GnomedDev commented on payload/sp/TrackPackManager.hh
> +    static WFixedString<64> s_name;
The system heap stays allocated? Could I put `TrackPackManager` in there and get rid of `TrackPackInfo` entirely?

2023-04-06 17:43 UTC, riidefi commented on payload/sp/TrackPackManager.hh
> +    static WFixedString<64> s_name;
It's better to keep the data in MEM2 and extend the structure you insert TrackPackManager into

2023-04-08 00:51 UTC, GnomedDev commented on payload/sp/TrackPackManager.hh
> +    WFixedString<64> name = {};
Hmm? That seems like a micro optimisation and even then, how would that be better for cache reason?

2023-04-10 02:08 UTC, riidefi requested changes

2023-04-10 02:08 UTC, riidefi commented on payload/sp/FixedString.hh
> +    constexpr WFixedString(std::string_view view) {
Probably better as a static function like `fromUTF8`, possibly returning an optional value down the road?

2023-04-10 02:08 UTC, riidefi commented on payload/sp/vanillaTracks.hh
> +constexpr std::string_view vanillaManifest = R"(
`#pragma once`

2023-04-10 02:08 UTC, riidefi commented on payload/game/system/MultiDvdArchive.hh
> +    void REPLACED(init)();
Maybe also pull this into its own PR as a bugfix?

2023-04-10 02:08 UTC, riidefi commented on payload/game/ui/SingleTopPage.cc
> +    auto coinEnabled = (supportedModes & SP::TrackGameMode::Coin) != SP::TrackGameMode::None;
`== SP::TrackGameMode::Coin` / similar for all of these is preferable as it handles flagsets too and it's not obvious `::None` is 0.

2023-04-10 12:09 UTC, GnomedDev commented on payload/sp/FixedString.hh
> +#include <string>
I have already messed this branch up with the first couple of commits, I don't want to push git any further to avoid having to merge it down into one commit.

2023-04-10 12:09 UTC, GnomedDev commented on payload/sp/FixedString.hh
>      std::array<char, N> m_buf = {};
Not in scope for this PR

2023-04-10 12:10 UTC, GnomedDev commented on payload/sp/vanillaTracks.hh
> +constexpr std::string_view vanillaManifest = R"(
I thought you said constexpr allows it be included multiple times?

2023-04-10 12:11 UTC, GnomedDev commented on payload/game/system/MultiDvdArchive.hh
> +    void REPLACED(init)();
It isn't a bugfix to upstream, as it isn't used in upstream. Just seems like mindless busywork.

2023-04-10 17:09 UTC, riidefi commented on payload/sp/vanillaTracks.hh
> +constexpr std::string_view vanillaManifest = R"(
All other header files in the repo begin with `#pragma once#. This one isn't special.

`constexpr` makes the definition weak which prevents linker ODR-violations if the file is included in multiple translation units. It's still not valid to multiply define the same weak symbol within singular translation unit.

2023-04-10 17:11 UTC, riidefi commented on payload/sp/FixedString.hh
>      std::array<char, N> m_buf = {};
We should clearly communicate our maximum size for fields in the `.ini`. In this case, when you wrote `FixedString<64>`, perhaps you meant `FixedString<65>` given this behavior?

2023-04-10 17:13 UTC, riidefi commented on payload/sp/FixedString.hh
> +#include <string>
This utility is useful beyond this PR (which cannot get merged for a while).

2023-04-10 17:50 UTC, GnomedDev commented on payload/sp/FixedString.hh
> +#include <string>
Okay?

2023-04-10 18:14 UTC, GnomedDev commented on payload/game/ui/SingleTopPage.cc
> +    auto coinEnabled = (supportedModes & SP::TrackGameMode::Coin) != SP::TrackGameMode::None;
Just tested, and in fact, `7 == 4` does not return True!

2023-04-10 18:39 UTC, riidefi commented on payload/sp/FixedString.hh
>      std::array<char, N> m_buf = {};
Gotcha. We should then enforce a limit of 63/whatever in the python wiimmdb parser.

2023-04-10 18:44 UTC, riidefi commented on payload/game/ui/SingleTopPage.cc
> +    auto coinEnabled = (supportedModes & SP::TrackGameMode::Coin) != SP::TrackGameMode::None;
> Just tested, and in fact, 7 == 4 does not return True!
Knock it off with the attitude. A flagset denotes a value like 0b0110 where ((0b0110 & 0b0110) != 0) == ((0b0110 & 0b0100) != 0) == ((0b0110 & 0b0010) != 0).

2023-04-10 18:56 UTC, riidefi commented on payload/game/ui/SingleTopPage.cc
> +    auto coinEnabled = (supportedModes & SP::TrackGameMode::Coin) != SP::TrackGameMode::None;
Here is some testing:
```py
>>> bool(7 & 4)
True
>>> bool(7 & 2)
True
>>> bool(7 & 1)
True
```

2023-04-10 20:04 UTC, GnomedDev commented on payload/game/ui/SingleTopPage.cc
> +    auto coinEnabled = (supportedModes & SP::TrackGameMode::Coin) != SP::TrackGameMode::None;
Isn't that literally it is doing though? 
> `(supportedModes & SP::TrackGameMode::Race)`

2023-04-10 20:23 UTC, riidefi commented on payload/game/ui/SingleTopPage.cc
> +    auto coinEnabled = (supportedModes & SP::TrackGameMode::Coin) != SP::TrackGameMode::None;
`(supportedModes & X) == X` is preferable here since for some `X = (1 << N) | (1 << M`), `N != M`, it only triggers when both bits intersect. `(supportedModes & X) != 0` triggers when either bit intersects. So generally in C++ when we are asking if a full condition is met in a bitfield, we almost always go with the former form.

2023-04-26 22:17 UTC, riidefi commented on payload/game/kart/KartTire.hh
> +#pragma once
Would pull this into its own PR like "Added missing #pragma once". Or if possible, can we not enforce this in clang-format?

2023-04-26 22:17 UTC, riidefi commented on payload/game/kart/KartTire.hh
> +#pragma once
(Since it touches a bunch of unrelated files)

2023-04-27 22:16 UTC, GnomedDev commented on payload/game/kart/KartTire.hh
> +#pragma once
I did this because you were being overly pedantic about it in the glorified ini file, pull into your own PR if you want but the script I made to find them is long gone.

2023-06-14 23:31 UTC, GnomedDev commented
Closing this PR as it is no longer relevant and unmergable due to conflicts and large diff. These changes will be rewritten into smaller PRs (805, 807, 832).

2023-06-14 23:31 UTC, closed without merging