Do not permit the use of a modified 'main.dol' file
stblr/mkw-sp pull request #659
Opened 2023-04-02 18:00 UTC by MikeIsAStar

2023-04-04 06:41 UTC, MikeIsAStar commented
This pull request is now ready for review @stblr.

2023-04-04 20:28 UTC, stblr requested changes

2023-04-04 20:28 UTC, stblr commented on configure.py
> +        os.path.join('vendor', 'clibs', 'sha1', 'sha1.c'),
What's the purpose of the `clibs` directory?

2023-04-04 20:28 UTC, stblr commented on loader/Loader.cc
> +}
```suggestion
extern "C" {
#include <vendor/clibs/sha1/sha1.h>
}
```

2023-04-04 20:28 UTC, stblr commented on loader/Dol.cc
> +static std::optional<u32> GetRegionIndex() {
We should try to use a consistent region order...

2023-04-04 20:28 UTC, stblr commented on loader/Loader.cc
> +#include "Dol.hh"
```suggestion
#include "loader/Dol.hh"
```

2023-04-04 20:28 UTC, stblr commented on loader/Apploader.cc
> +        memset((void *)Dol::GetStartAddress(), 0, *dolSize);
`const_cast`?

2023-04-04 20:28 UTC, stblr commented on loader/Apploader.cc
> +#include "Dol.hh"
```suggestion
#include "loader/Dol.hh"
```

2023-04-04 21:18 UTC, MikeIsAStar commented on configure.py
> +        os.path.join('vendor', 'clibs', 'sha1', 'sha1.c'),
Resolved in commit [0c18826](https://github.com/stblr/mkw-sp/pull/659/commits/0c18826c45a999dbfdbc3268248d724d5700441f).

2023-04-04 21:18 UTC, MikeIsAStar commented on loader/Loader.cc
> +}
Resolved in commit [0c18826](https://github.com/stblr/mkw-sp/pull/659/commits/0c18826c45a999dbfdbc3268248d724d5700441f).

2023-04-04 21:18 UTC, MikeIsAStar commented on loader/Dol.cc
> +static std::optional<u32> GetRegionIndex() {
Resolved in commit [0c18826](https://github.com/stblr/mkw-sp/pull/659/commits/0c18826c45a999dbfdbc3268248d724d5700441f).

2023-04-04 21:18 UTC, MikeIsAStar commented on loader/Apploader.cc
> +        memset((void *)Dol::GetStartAddress(), 0, *dolSize);
Resolved in commit [0c18826](https://github.com/stblr/mkw-sp/pull/659/commits/0c18826c45a999dbfdbc3268248d724d5700441f).

2023-04-04 21:19 UTC, MikeIsAStar commented on loader/Apploader.cc
> +#include "Dol.hh"
Resolved in commit [0c18826](https://github.com/stblr/mkw-sp/pull/659/commits/0c18826c45a999dbfdbc3268248d724d5700441f).

2023-04-05 18:10 UTC, stblr approved these changes

2023-04-05 18:10 UTC, merged

2023-04-07 08:12 UTC, Maidvelia commented
If main.dol cannot be edited then a separate option to disable the deflicker should be put in.