Add text scrolling to the visual console
stblr/mkw-sp pull request #670
Opened 2023-04-06 04:40 UTC by MikeIsAStar

2023-04-23 21:16 UTC, stblr commented
I did not test it but are you sure this is scrolling? It rather looks like the scrolling loop would not longer be reachable.

The interlaced mode changes should at the very least be moved to a separate commit.

2023-04-24 18:49 UTC, stblr requested changes

2023-04-24 18:49 UTC, stblr commented on common/Console.cc
> +    if (col > cols && c != '\n' && c != '\r') {
```suggestion
    if (col >= cols) {
```

2023-04-24 18:49 UTC, stblr commented on common/Console.cc
>          return;
```suggestion
        row++;

        return;
```
This break things e.g. if `Console::Print("\n\n")` is called while the console is already full. I don't think that was your intent here.

2023-04-25 03:28 UTC, MikeIsAStar commented on common/Console.cc
> +    if (col > cols && c != '\n' && c != '\r') {
Corrected in commit [6ff7b0b](https://github.com/stblr/mkw-sp/pull/670/commits/6ff7b0b67a312fa1966f90a93c6c7aa21ab251d5).

2023-04-25 03:28 UTC, MikeIsAStar commented on common/Console.cc
>          return;
Corrected in commit [6ff7b0b](https://github.com/stblr/mkw-sp/pull/670/commits/6ff7b0b67a312fa1966f90a93c6c7aa21ab251d5).

2023-04-25 17:05 UTC, stblr approved these changes

2023-04-25 17:06 UTC, merged