Rewrite KartObjectManager in C++
stblr/mkw-sp pull request #675
Opened 2023-04-11 15:42 UTC by GnomedDev

Allows us to get rid of a lot of C bindings for this stuff

2023-04-17 19:20 UTC, stblr commented on payload/game/kart/KartObjectManager.cc
> +    }
Does this mean that the setting can be changed between races?

2023-04-18 09:33 UTC, GnomedDev commented on payload/game/kart/KartObjectManager.cc
> +    }
Yes, just tested and it does.

2023-04-19 18:30 UTC, stblr requested changes

2023-04-19 18:30 UTC, stblr commented on payload/game/kart/KartObjectManager.cc
> +    }
That's a bug then.

2023-04-19 19:01 UTC, GnomedDev commented on payload/game/kart/KartObjectManager.cc
> +    }
How come? Sounds like a feature?

2023-04-19 19:08 UTC, stblr commented on payload/game/kart/KartObjectManager.cc
> +    }
That's not consistent with the other engine classes.

2023-04-19 19:10 UTC, GnomedDev commented on payload/game/kart/KartObjectManager.cc
> +    }
Those other classes are just bugged due to #662, this is moving towards the right behavior (even if it is inconsistent in the mean time)

2023-04-19 19:12 UTC, GnomedDev commented on payload/game/kart/KartObjectManager.cc
> +    }
Intended behavior is that changing settings during a race does not change them until the single top page is passed through again? Do you want me to open issues for the settings that don't match this behavior?

2023-04-19 19:14 UTC, stblr commented on payload/game/kart/KartObjectManager.cc
> +    }
All VS and battle settings already match that behavior AFAIK.

2023-04-19 19:15 UTC, GnomedDev commented on payload/game/kart/KartObjectManager.cc
> +    }
Okay, I'll "fix" this and look for somewhere to document it.

2023-04-19 19:16 UTC, stblr commented on payload/game/kart/KartObjectManager.cc
> +    }
This is just how the base game works...

2023-04-19 19:20 UTC, stblr commented on payload/game/kart/KartObjectManager.cc
> +    }
Conceptually all the races in a VS game are supposed to have the same rules (with e.g. the engine class being shown in the awards). The only issue with what we have now is that it is confusing to show the VS settings in race because they will only be applied for the next game.

2023-04-19 20:22 UTC, stblr commented on payload/game/system/RaceConfig.hh
> +    u8 _0007[0x0020 - 0x0007];
I would maybe put it in `MenuScenario` with the other flags. I'm also not sure where this offset change comes from.

2023-04-19 20:25 UTC, GnomedDev commented on payload/game/system/RaceConfig.hh
> +    u8 _0007[0x0020 - 0x0007];
The first 0x4 bytes is the vtable, which although it doesn't get called, I didn't want to randomly overwrite it. Putting it in `m_menuScenario` would work but then it looks like it's duplicated throughout the different Scenarios, which isn't true as it is only touched in the one (eg: perfect for just being part of `RaceConfig`)

2023-04-19 20:30 UTC, stblr commented on payload/game/system/RaceConfig.hh
> +    u8 _0007[0x0020 - 0x0007];
It's more for consistency than anything.

2023-04-20 19:26 UTC, riidefi requested changes

2023-04-20 19:26 UTC, riidefi commented on vendor/sha1/sha1.c
> +
Move to its own PR

2023-04-20 20:13 UTC, GnomedDev commented on vendor/sha1/sha1.c
> +
Cope

2023-04-20 23:53 UTC, vabold commented on vendor/sha1/sha1.c
> +
> Cope

Knock it off with the attitude.

2023-04-24 08:19 UTC, riidefi commented on payload/game/system/RaceConfig.hh
> +    u8 _0007[0x0020 - 0x0007];
Probably more readable to have the flags in one place? Jury may still be out on the proper place for them, but that seems beyond the scope of this PR.

2023-04-24 19:03 UTC, GnomedDev commented on payload/game/system/RaceConfig.hh
> +    u8 _0007[0x0020 - 0x0007];
What do you mean "the flags"?

2023-04-25 22:26 UTC, stblr approved these changes

2023-04-25 22:27 UTC, merged