Rewrite RaceMenuPage to C++
stblr/mkw-sp pull request #679
Opened 2023-04-11 22:11 UTC by GnomedDev

2023-04-17 19:41 UTC, stblr requested changes

2023-04-17 19:41 UTC, stblr commented on payload/game/ui/page/VsRaceMenuPage.hh
> +#include "RaceMenuPage.hh"
```suggestion
#include "game/ui/page/RaceMenuPage.hh"
```

2023-04-17 19:41 UTC, stblr commented on payload/game/util/Registry.hh
> +#define ENABLE_MR false
I think this should only control the buttons in the `SingleTopPage` to keep the differences as minimal as possible.

2023-04-17 19:41 UTC, stblr commented on payload/game/ui/page/ToRaceMenuPage.hh
> +#include "RaceMenuPage.hh"
```suggestion
#include "game/ui/page/RaceMenuPage.hh"
```

2023-04-17 19:41 UTC, stblr commented on payload/game/ui/page/TaRaceMenuPage.hh
> +#include "RaceMenuPage.hh"
```suggestion
#include "game/ui/page/RaceMenuPage.hh"
```

2023-04-17 19:41 UTC, stblr commented on payload/game/ui/page/ReplayGhostRaceMenuPage.hh
> +#include "RaceMenuPage.hh"
```suggestion
#include "game/ui/page/RaceMenuPage.hh"
```

2023-04-17 19:41 UTC, stblr commented on payload/game/ui/page/GhostWatchRaceMenuPage.hh
> +#include "RaceMenuPage.hh"
```suggestion
#include "game/ui/page/RaceMenuPage.hh"
```

2023-04-17 19:41 UTC, stblr commented on payload/game/ui/page/BtRaceMenuPage.hh
> +#include "RaceMenuPage.hh"
```suggestion
#include "game/ui/page/RaceMenuPage.hh"
```

2023-04-17 19:41 UTC, stblr commented on payload/game/ui/page/AfterTaRaceMenuPage.hh
> +#include "RaceMenuPage.hh"
```suggestion
#include "game/ui/page/RaceMenuPage.hh"
```

2023-04-18 09:53 UTC, GnomedDev commented on payload/game/util/Registry.hh
> +#define ENABLE_MR false
Okay, I'll revert back the guards on other stuff

2023-04-18 21:07 UTC, stblr approved these changes

2023-04-18 21:07 UTC, merged