Rewrite HomeButton in C++
stblr/mkw-sp pull request #685
Opened 2023-04-12 20:38 UTC by GnomedDev

2023-04-17 19:24 UTC, stblr requested changes

2023-04-17 19:24 UTC, stblr commented on payload/game/host_system/SystemManager.cc
> +#include "game/ui/Section.hh"
```suggestion

#include "game/host_system/Scene.hh"
#include "game/system/RaceManager.hh"
#include "game/ui/Section.hh"
```

2023-04-17 19:24 UTC, stblr commented on payload/game/host_system/SystemManager.hh
> +#include "game/ui/SectionId.hh"
Wait, is this needed?

2023-04-18 09:35 UTC, GnomedDev commented on payload/game/host_system/SystemManager.hh
> +#include "game/ui/SectionId.hh"
Yes, as is, as `RichPresenceManager::onSectionChange` takes a `SectionId`

2023-04-18 21:04 UTC, stblr approved these changes

2023-04-18 21:05 UTC, merged