Remove LogFile.h
stblr/mkw-sp pull request #686
Opened 2023-04-18 23:20 UTC by GnomedDev

This removes the unnecessary pass through `extern "C"`

2023-04-19 20:25 UTC, stblr commented
It's fine if C++ code is added to `payload/revolution`.

2023-04-24 18:10 UTC, stblr requested changes

2023-04-24 18:10 UTC, stblr commented on payload/revolution/os/OSError.cc
>  #include <string.h>
```suggestion
#include <cstdio>
#include <cstring>
```

2023-04-24 18:10 UTC, stblr commented on payload/revolution/os/OSError.cc
> +
```suggestion
```
Or add a newline at the end.

2023-04-24 18:57 UTC, GnomedDev commented on payload/revolution/os/OSError.cc
> +REPLACE void OSReport(const char *msg, ...) {
`OSPanic` was already using `REPLACE` in the c file, how come I should create a header for this? (other than consistency)

2023-04-24 21:30 UTC, stblr approved these changes

2023-04-24 21:30 UTC, merged