Cherry-pick / un-GPT ShaUtil
stblr/mkw-sp pull request #701
Opened 2023-04-27 01:12 UTC by riidefi

2023-04-27 01:15 UTC, GnomedDev commented
I dislike the Write/Read names, maybe make a class with a constructor and a toString method.

2023-04-27 01:18 UTC, GnomedDev requested changes

2023-04-27 01:18 UTC, GnomedDev commented on payload/sp/ShaUtil.hh
> +FixedString<0x28 + 1> WriteSHA1(std::span<const u8, 0x14> bytes);
Using FixedString is redundant as the length is always equal to the capacity. Just use a regular array.

2023-04-27 01:18 UTC, GnomedDev commented on payload/sp/ShaUtil.cc
> +        snprintf(&hex.m_buf[i * 2], 3, "%02x", bytes[i]);
Should this be split out into HexParser?

2023-04-27 01:20 UTC, riidefi commented
I'll revert back to SHA1ToHex, SHA1FromHex

2023-04-27 01:22 UTC, riidefi commented on payload/sp/ShaUtil.cc
> +        snprintf(&hex.m_buf[i * 2], 3, "%02x", bytes[i]);
I think we can drop HexParser and replace with https://en.cppreference.com/w/cpp/utility/to_chars

2023-04-27 01:34 UTC, riidefi commented on payload/sp/ShaUtil.hh
> +FixedString<0x28 + 1> WriteSHA1(std::span<const u8, 0x14> bytes);
That's true. But 4 bytes is probably not that much overhead; probably worth the trade-off for the cleaner interface? If we really wanted to be efficient we would be working with a templated output iterator anyway.

2023-04-27 06:23 UTC, GnomedDev commented on payload/sp/ShaUtil.hh
> +FixedString<0x28 + 1> WriteSHA1(std::span<const u8, 0x14> bytes);
What cleaner interface? The problem with splitting this out into it's own commit is it is void of context. In track-packs, I cannot remember a time where I needed to do anything but `.data()` on the array returned back.

2023-05-01 19:15 UTC, riidefi commented
I think neither of us knew of such a set of function's existence.

2023-05-01 19:23 UTC, GnomedDev commented
Oh, huh, yeah never knew that existed

2023-05-02 21:21 UTC, riidefi commented
Closing in favor of `hydro_bin2hex` and friends

2023-05-02 21:21 UTC, closed without merging