Tidy: Implement skeleton
stblr/mkw-sp pull request #712
Opened 2023-04-30 23:35 UTC by GnomedDev

This PR implements the basics needed for `tidy`, a script to run in CI to check for correctness. I have already written checks for `#pragma once` usage and python formatting, outside of this PR but any correctness PR would be free to add a check to tidy.

2023-05-02 22:34 UTC, stblr requested changes

2023-05-02 22:34 UTC, stblr commented on tools/tidy/main.py
> +        changed_raw = subprocess.check_output(["git", "diff-tree", "--no-commit-id", "--name-only", "HEAD~", "-r"]).decode()
This returns the changed files of the penultimate commit.

If you want an option to diff only certain files, I would suggest to pass them to the script with a command line argument which would be the most flexible.

2023-05-02 22:48 UTC, GnomedDev commented on tools/tidy/main.py
> +        changed_raw = subprocess.check_output(["git", "diff-tree", "--no-commit-id", "--name-only", "HEAD~", "-r"]).decode()
Fair, this idea got less and less useful as I thought about it

2023-05-05 18:54 UTC, stblr requested changes

2023-05-05 18:54 UTC, stblr commented on tools/tidy/README.md
> +To run locally, make sure you are in the root of the project and run `python3 main.py`.
```suggestion
To run locally, make sure you are in the root of the project and run `python3 tools/tidy/main.py`.
```

2023-05-06 22:03 UTC, stblr approved these changes

2023-05-06 22:04 UTC, merged