Print the names of functions and variables to the exception console
stblr/mkw-sp pull request #715
Opened 2023-05-03 16:30 UTC by MikeIsAStar

2023-05-03 18:30 UTC, stblr requested changes
Cool stuff!

2023-05-03 18:30 UTC, stblr commented on payload/egg/core/eggSystem.hh
> +    u32 _14;
```suggestion
    u8 _14[0x18 - 0x14];
```

2023-05-03 18:30 UTC, stblr commented on payload/game/host_system/RkSystem.cc
> +    SP::MapFile::Load();
Why here?

2023-05-03 18:30 UTC, stblr commented on payload/nw4r/db/dbException.cc
> +typedef struct {
```suggestion
struct ExceptionInfo {
```

2023-05-03 18:30 UTC, stblr commented on payload/nw4r/db/dbException.cc
> +} ExceptionInfo;
```suggestion
};
```

2023-05-03 18:30 UTC, stblr commented on payload/nw4r/db/dbException.cc
> +        Exception_Printf_("---EXCEPTION_INFO_GPR---\n");
"MAIN"?

2023-05-03 18:30 UTC, stblr commented on payload/platform/isdigit.c
> +#endif
Are you sure this hack is needed?

2023-05-03 18:30 UTC, stblr commented on payload/sp/ExceptionSyms.cc
> +#include <bits/functexcept.h>
Is the function declared in this file?

2023-05-03 18:30 UTC, stblr commented on payload/sp/MapFile.cc
> +#elif defined(SP_TEST)
This cannot be defined.

2023-05-03 18:30 UTC, stblr commented on payload/sp/MapFile.cc
> +            &bytesRead, nullptr));
It might be simpler to add the `ro:` prefix to the paths and to use `Storage::ReadFile`.

2023-05-03 18:30 UTC, stblr commented on payload/sp/MapFile.cc
> +        OSReport("[MAP] Failed to read the map file '%s'!\n", mapFilePath);
Why no `SP_LOG`?

2023-05-03 18:30 UTC, stblr commented on payload/sp/MapFile.cc
> +}
Do we need this function?

2023-05-03 18:30 UTC, stblr commented on payload/sp/MapFile.cc
> +static std::optional<std::string_view> sMapFile = {};
```suggestion
static std::optional<std::string_view> s_mapFile = {};
```

2023-05-03 19:00 UTC, MikeIsAStar commented on payload/game/host_system/RkSystem.cc
> +    SP::MapFile::Load();
The previous function is responsible for initialising the heap that is used.

2023-05-03 19:02 UTC, MikeIsAStar commented on payload/sp/ExceptionSyms.cc
> +}
`substr`

2023-05-03 19:22 UTC, MikeIsAStar commented on payload/sp/MapFile.cc
> +#elif defined(SP_TEST)
Can't the following code define it ?

https://github.com/stblr/mkw-sp/blob/main/build.py#L971-L989

2023-05-03 19:32 UTC, vabold commented on payload/sp/MapFile.cc
> +        OSReport("[MAP] Failed to read the map file '%s'!\n", mapFilePath);
Because he's Star. I'm pretty sure he would use `uint32_t` if given the chance.

2023-05-03 19:49 UTC, vabold commented on payload/game/host_system/RkSystem.cc
> +    SP::MapFile::Load();
In addition to this, the replacement I suggested (`SystemManager::loadSymbols`) is not called on startup anymore because we skip the strap scene.

2023-05-03 19:49 UTC, vabold commented on payload/egg/core/eggSystem.cc
>  }
This function already exists in-game and as such should use a replacement.

2023-05-03 19:50 UTC, vabold commented on payload/game/host_system/RkSystem.cc
> +    SP::MapFile::Load();
In addition to this, the replacement I suggested (`SystemManager::loadSymbols`) is not called on startup anymore because we skip the strap scene.

2023-05-03 21:49 UTC, riidefi commented on payload/sp/MapFile.cc
> +    if (!IsCharacterSpace(line)) {
`line.starts_with(' ')`

2023-05-03 21:53 UTC, riidefi commented on payload/sp/MapFile.cc
> +    size_t lineStartIndex = line.find_first_not_of('\n');
Can we assume carriage-returns always precede new-lines?

2023-05-04 00:02 UTC, MikeIsAStar commented on payload/sp/MapFile.cc
> +    size_t lineStartIndex = line.find_first_not_of('\n');
The file `symbols.txt` does not use a `carriage return` character to denote a new line.

2023-05-04 00:04 UTC, MikeIsAStar commented on payload/platform/isdigit.c
> +#endif
It would appear so.

2023-05-04 00:05 UTC, MikeIsAStar commented on payload/platform/isxdigit.c
> +#endif
It would appear so.

2023-05-04 03:00 UTC, MikeIsAStar commented on payload/nw4r/db/dbException.cc
> +typedef struct {
Resolved in commit [8a74e62](https://github.com/stblr/mkw-sp/pull/715/commits/8a74e627f677106cea841c2666a128fa8844b940).

2023-05-04 03:00 UTC, MikeIsAStar commented on payload/nw4r/db/dbException.cc
> +} ExceptionInfo;
Resolved in commit [8a74e62](https://github.com/stblr/mkw-sp/pull/715/commits/8a74e627f677106cea841c2666a128fa8844b940).

2023-05-04 03:00 UTC, MikeIsAStar commented on payload/nw4r/db/dbException.cc
> +        Exception_Printf_("---EXCEPTION_INFO_GPR---\n");
Resolved in commit [8a74e62](https://github.com/stblr/mkw-sp/pull/715/commits/8a74e627f677106cea841c2666a128fa8844b940).

2023-05-04 03:00 UTC, MikeIsAStar commented on payload/sp/ExceptionSyms.cc
> +#include <bits/functexcept.h>
Resolved in commit [8a74e62](https://github.com/stblr/mkw-sp/pull/715/commits/8a74e627f677106cea841c2666a128fa8844b940).

2023-05-04 03:00 UTC, MikeIsAStar commented on payload/sp/MapFile.cc
> +#elif defined(SP_TEST)
Resolved in commit [8a74e62](https://github.com/stblr/mkw-sp/pull/715/commits/8a74e627f677106cea841c2666a128fa8844b940).

2023-05-04 03:02 UTC, MikeIsAStar commented on payload/sp/MapFile.cc
> +            &bytesRead, nullptr));
Resolved in commit [8a74e62](https://github.com/stblr/mkw-sp/pull/715/commits/8a74e627f677106cea841c2666a128fa8844b940).

2023-05-04 03:02 UTC, MikeIsAStar commented on payload/sp/MapFile.cc
> +        OSReport("[MAP] Failed to read the map file '%s'!\n", mapFilePath);
Resolved in commit [8a74e62](https://github.com/stblr/mkw-sp/pull/715/commits/8a74e627f677106cea841c2666a128fa8844b940).

2023-05-04 03:02 UTC, MikeIsAStar commented on payload/sp/MapFile.cc
> +}
Resolved in commit [8a74e62](https://github.com/stblr/mkw-sp/pull/715/commits/8a74e627f677106cea841c2666a128fa8844b940).

2023-05-04 03:05 UTC, MikeIsAStar commented on payload/sp/MapFile.cc
> +static std::optional<std::string_view> sMapFile = {};
Resolved in commit [8a74e62](https://github.com/stblr/mkw-sp/pull/715/commits/8a74e627f677106cea841c2666a128fa8844b940).

2023-05-04 03:05 UTC, MikeIsAStar commented on payload/sp/MapFile.cc
> +    std::string_view line = sMapFile->substr(mapFilePos, sMapFile->size());
Resolved in commit [8a74e62](https://github.com/stblr/mkw-sp/pull/715/commits/8a74e627f677106cea841c2666a128fa8844b940).

2023-05-04 03:05 UTC, MikeIsAStar commented on payload/egg/core/eggSystem.cc
>  }
Resolved in commit [8a74e62](https://github.com/stblr/mkw-sp/pull/715/commits/8a74e627f677106cea841c2666a128fa8844b940).

2023-05-04 03:05 UTC, MikeIsAStar commented on payload/sp/MapFile.cc
> +    if (!IsCharacterSpace(line)) {
Resolved in commit [8a74e62](https://github.com/stblr/mkw-sp/pull/715/commits/8a74e627f677106cea841c2666a128fa8844b940).

2023-05-04 18:24 UTC, stblr approved these changes

2023-05-04 18:24 UTC, merged