Rewrite ItemCommand to C++
stblr/mkw-sp pull request #728
Opened 2023-05-10 16:31 UTC by GnomedDev

2023-05-30 19:04 UTC, riidefi commented on payload/sp/ItemCommand.cc
> +    if (!strncmp(args, "/i ", strlen("/i "))) {
Flip if statement

2023-05-30 19:05 UTC, riidefi commented on payload/sp/ItemCommand.cc
> +            qty = MAX(-qty, 1);
In C++ we can use std::max

2023-05-30 19:06 UTC, riidefi commented on payload/sp/ItemCommand.cc
> +s8 GetMyPlayerID(void) {
`int` not `s8`

2023-05-30 19:07 UTC, riidefi commented on payload/sp/ItemCommand.cc
> +            auto &stickyState = s_sticky.emplace();
s_sticky.emplace() = {
.item = ...,
.quantity = ...
};

2023-05-31 19:48 UTC, GnomedDev commented on payload/sp/ItemCommand.cc
> +s8 GetMyPlayerID(void) {
Why? It isn't ever going to be above 127.

2023-05-31 19:56 UTC, riidefi commented on payload/sp/ItemCommand.cc
> +s8 GetMyPlayerID(void) {
You're right; I misread it as an implicit narrowing type conversion.

2023-05-31 20:06 UTC, GnomedDev commented on payload/sp/ItemCommand.cc
> +std::optional<ItemCommand::StickyState> ItemCommand::s_sticky = std::nullopt;
I've seen it done both ways.

2023-05-31 22:29 UTC, riidefi approved these changes

2023-06-01 02:40 UTC, MikeIsAStar commented on payload/sp/ItemCommand.cc
> +s8 GetMyPlayerID(void) {
```suggestion
static s8 GetMyPlayerID() {
```

2023-06-01 05:39 UTC, vabold requested changes

2023-06-01 05:39 UTC, vabold commented on payload/sp/ItemCommand.cc
> +    auto &raceScenario = raceConfig->raceScenario();
```suggestion
    auto &raceScenario = System::RaceConfig::Instance()->raceScenario();
```
RaceConfig is preserved through all scenes and is created on game start.

2023-06-01 05:39 UTC, vabold commented on payload/sp/ItemCommand.cc
> +    s8 playerId = raceScenario.screenPlayerIds[0];
The error message suggests that the expected behavior is for the screen player ID to be a valid, real player. We should verify the type of player is real local or clarify the expected behavior in the error message.

2023-06-01 10:04 UTC, GnomedDev commented on payload/sp/ItemCommand.cc
> +    auto &raceScenario = raceConfig->raceScenario();
This code really was busted before I rewrote it.

2023-06-01 12:37 UTC, GnomedDev commented on payload/sp/ItemCommand.cc
> +    auto &raceScenario = raceConfig->raceScenario();
I'll reimplement an actual check after #803 allows me to get the SceneManager.

2023-06-01 12:44 UTC, vabold commented on payload/sp/ItemCommand.cc
> +    auto &raceScenario = raceConfig->raceScenario();
Actually, we can use the section ID to do this.

2023-06-03 22:27 UTC, stblr approved these changes

2023-06-03 22:28 UTC, merged