Implement vanilla vehicle restrictions
stblr/mkw-sp pull request #731
Opened 2023-05-12 23:15 UTC by GnomedDev

Undoes the regression made by adding the new settings menu, but does not implement further filtering due to added complexity.

2023-05-14 16:20 UTC, stblr requested changes

2023-05-14 16:20 UTC, stblr commented on payload/sp/settings/ClientSettings.hh
> -    Random,
Please comment them out like the rest.

2023-05-14 16:20 UTC, stblr commented on payload/game/ui/SingleTopPage.cc
> -
What happens in time trials?

2023-05-14 16:20 UTC, stblr commented on payload/game/ui/MultiTopPage.cc
> +    context->m_vehicleRestriction = GlobalContext::VehicleRestriction::All;
Can you also implement the restrictions in multiplayer?

2023-05-14 17:54 UTC, GnomedDev commented on payload/game/ui/SingleTopPage.cc
> -
It only affects CPU drivers, so nothing happens.

2023-05-15 18:17 UTC, stblr approved these changes

2023-05-15 18:17 UTC, merged