Rewrite the file 'Heap.c' in C++
stblr/mkw-sp pull request #736
Opened 2023-05-15 01:05 UTC by MikeIsAStar

2023-05-15 01:21 UTC, vabold requested changes

2023-05-15 01:21 UTC, vabold commented on payload/sp/Payload.cc
> +    SP::Heap::RandomizeMEM2Heaps();
As evidenced by `GlobalSettings::Init()` in the same function, the `SP` namespace in these calls is not required.

`SP::LogFile::Init()` can also be changed to `LogFile::Init()` to reflect this.

2023-05-15 02:36 UTC, MikeIsAStar commented on payload/sp/Payload.cc
> +    SP::Heap::RandomizeMEM2Heaps();
Resolved in commit [0c488ff](https://github.com/stblr/mkw-sp/pull/736/commits/0c488ffa1c175d438af30cac3588ce406b4915c8).

2023-05-23 19:55 UTC, stblr approved these changes

2023-05-23 19:55 UTC, merged