Readd the 'Rankings' section
stblr/mkw-sp pull request #745
Opened 2023-05-19 02:30 UTC by MikeIsAStar

This commit aims to readd the 'Rankings' section to the game.

The following issues should be addressed before this commit is merged:
* [ ] Fix the Mii of a player not appearing on the histogram, even when the method `selectSPLicense` is called
* [ ] Fix the crash that occurs when attempting to change the course
* [ ] Fix the crash that occurs when attempting to start a Time Trial
* [ ] Replace the textbox that appears when an attempt is made to download the ghost of a champion

2023-05-19 03:10 UTC, vabold commented
The section loaded when attempting to start a time trial is 0x4F.

2023-05-26 20:49 UTC, stblr commented
Would feature gating make sense here?

2023-05-26 20:54 UTC, vabold commented
> Would feature gating make sense here?

There is (untested) present functionality here, so I do not believe so.

2023-05-26 21:03 UTC, vabold requested changes

2023-05-26 21:03 UTC, vabold commented on payload/game/ui/RankingPage.cc
> +}
Ordering.

2023-05-26 21:03 UTC, stblr requested changes

2023-05-26 21:03 UTC, stblr commented on payload/game/ui/CourseSelectPage.cc
> +    if (m_blackBackControl) {
This is not initialized to `nullptr` if `ranking` is false. I would suggest using `unique_ptr`.

2023-05-26 21:03 UTC, stblr commented on payload/game/ui/CourseSelectPage.cc
> +
```suggestion
#include "game/util/Registry.hh"

```

2023-05-26 21:03 UTC, stblr commented on payload/game/ui/CourseSelectPage.cc
> -#include "game/system/RaceConfig.hh"
Revert.

2023-05-26 21:10 UTC, vabold commented on payload/game/util/Registry.hh
> +s32 GetButtonIndexFromCourse(Course course);
It is not a base game function, so the function is that specific.

There is a base game function which does the reverse - getting the course from the button index. It is called by `RankingPage::onInit` and only there.

It may not be part of the same TU, but there is a similar function named `WifiErrorExplain` which is in the same TU as the aforementioned base game function.

2023-05-27 14:38 UTC, MikeIsAStar commented on payload/game/ui/RankingPage.hh
> +    void setCourseId(u32 courseId);
Resolved in commit [3cffc6e](https://github.com/stblr/mkw-sp/pull/745/commits/3cffc6e63bb930dd0f92e51a65df0e4b8aa96fc5).

2023-05-27 14:38 UTC, MikeIsAStar commented on payload/game/ui/RankingPage.cc
> +}
Resolved in commit [3cffc6e](https://github.com/stblr/mkw-sp/pull/745/commits/3cffc6e63bb930dd0f92e51a65df0e4b8aa96fc5).

2023-05-27 14:39 UTC, MikeIsAStar commented on payload/game/ui/page/TopMenuPage.S
> +PATCH_REPLACE_END(TopMenuPage_onButtonFront, 0x1BC)
Resolved in commit [3cffc6e](https://github.com/stblr/mkw-sp/pull/745/commits/3cffc6e63bb930dd0f92e51a65df0e4b8aa96fc5).

2023-05-27 14:39 UTC, MikeIsAStar commented on payload/game/ui/CourseSelectPage.cc
> +    if (m_blackBackControl) {
Resolved in commit [3cffc6e](https://github.com/stblr/mkw-sp/pull/745/commits/3cffc6e63bb930dd0f92e51a65df0e4b8aa96fc5).

2023-05-27 14:39 UTC, MikeIsAStar commented on payload/game/ui/CourseSelectPage.cc
> +
Resolved in commit [3cffc6e](https://github.com/stblr/mkw-sp/pull/745/commits/3cffc6e63bb930dd0f92e51a65df0e4b8aa96fc5).

2023-05-27 14:39 UTC, MikeIsAStar commented on payload/game/ui/CourseSelectPage.cc
> -#include "game/system/RaceConfig.hh"
Resolved in commit [3cffc6e](https://github.com/stblr/mkw-sp/pull/745/commits/3cffc6e63bb930dd0f92e51a65df0e4b8aa96fc5).

2023-05-27 21:25 UTC, stblr commented
2 issues I found while testing:

- Online mode is no longer feature gated.
- When selecting a track with the `UpDownControl`, the selection in the `CourseSelectPage` is not updated.

2023-05-27 22:00 UTC, vabold commented
> > Would feature gating make sense here?
> 
> There is (untested) present functionality here, so I do not believe so.

After testing, there is no present functionality. I agree that this should be feature gated (temporary though it may be).

2023-05-29 00:12 UTC, stblr commented
The online buttons are no longer visible.

2023-05-29 02:45 UTC, MikeIsAStar commented
> The online buttons are no longer visible.

Resolved in commit [ee5ca0d](https://github.com/stblr/mkw-sp/pull/745/commits/ee5ca0dee39680cddfe6943580ba6c48bcfd9af3).

2023-05-29 21:02 UTC, stblr commented
The ifdef is flipped.

2023-05-29 21:42 UTC, MikeIsAStar commented
> The ifdef is flipped.

Resolved in commit [22533f6](https://github.com/stblr/mkw-sp/pull/745/commits/22533f613de30e1a0272d69055e6197fa0e90635).

2023-05-30 18:25 UTC, stblr approved these changes

2023-05-30 18:26 UTC, merged