Stub all ParameterFile functions
stblr/mkw-sp pull request #780
Opened 2023-05-26 09:01 UTC by GnomedDev

This allows for safe usage of the first 0x16 bytes of RaceConfig (after the vtable).

2023-05-28 21:34 UTC, vabold requested changes

2023-05-28 21:34 UTC, vabold commented on payload/game/system/RaceConfig.hh
>      u8 _0004[0x0020 - 0x0004];
The destructor must be replaced before it is safe to use 0x04 - 0x1c. `DestroyInstance` must be replaced before it is safe to use 0x1c - 0x20.

2023-05-29 20:37 UTC, stblr commented on payload/game/system/RaceConfig.hh
>      u8 _0004[0x0020 - 0x0004];
There is also a vtable access in `RaceConfig::init`.

2023-05-29 20:52 UTC, vabold commented on payload/game/system/RaceConfig.hh
>      u8 _0004[0x0020 - 0x0004];
The vtable access in `init` is fine because the dereference at 0x0 is valid. We simply stub the function.

2023-05-31 20:12 UTC, GnomedDev commented
This doesn't seem worth it.

2023-05-31 20:12 UTC, closed without merging