Page ID extension
stblr/mkw-sp pull request #788
Opened 2023-05-29 07:37 UTC by riidefi

2023-05-29 09:18 UTC, vabold requested changes

2023-05-29 09:18 UTC, vabold commented on payload/game/ui/Page.cc
> +}
Seems unnecessary.

2023-05-29 09:18 UTC, vabold commented on payload/game/host_system/SystemManager.hh
> +private:
Maybe a getter function would be preferred here.

2023-05-29 09:18 UTC, vabold commented on payload/game/ui/Section.cc
> +    }
```suggestion
    cullActivePages(0);
```
We can use the existing base game helper function at 806232e8.

The behavior here is also incorrect, as we do not set the page to a nullptr in this loop.

2023-05-29 09:18 UTC, vabold commented on payload/game/ui/Section.cc
> +    }
This loop is not required.

2023-05-29 09:18 UTC, vabold commented on payload/game/ui/Section.cc
> +        if (page == nullptr) {
```suggestion
    for (auto *&page : m_pages) {
        if (!page) {
```
Along with similar changes in this function.

I think an implicit nullptr check is fine in this context as there is no confusion - the page either exists or it doesn't.

2023-05-29 09:18 UTC, vabold commented on payload/game/ui/SectionManager.cc
> +extern "C" void RegisteredPadManage_onCreateSection(void *, bool);
```suggestion
extern "C" void RegisteredPadManager_onCreateSection(void *, bool);
```

2023-05-29 09:18 UTC, vabold commented on payload/game/ui/PageId.hh
> +}
Can we put this in a `UI::PageId` namespace or something similar?

2023-05-29 09:18 UTC, vabold commented on payload/game/ui/SectionManager.cc
> +    RegisteredPadManage_onCreateSection(&m_registeredPadManager, !race);
```suggestion
    RegisteredPadManager_onCreateSection(&m_registeredPadManager, !race);
```

2023-05-29 09:20 UTC, vabold commented
Nice work with the SectionManager field finding and the extension. Does Clang handle the `offsetof` correctly without pragmas?

2023-05-29 09:30 UTC, riidefi commented on payload/game/ui/Section.cc
> +        if (page == nullptr) {
I think I prefer `nullptr`

2023-05-29 09:32 UTC, riidefi commented on payload/game/ui/PageId.hh
> +}
This seems tacky

2023-05-29 09:38 UTC, vabold commented on payload/game/ui/PageId.hh
> +}
This is not an uncommon practice in the repository. The `SP` namespace notably has `Channel`, `IOSDolphin`, `MapFile`, etc. with similar functionality.

2023-05-29 09:39 UTC, riidefi commented on payload/game/ui/Section.cc
> +    }
I don't think the behavior is incorrect in this context. We can use the helper, though.

2023-05-29 09:40 UTC, vabold commented on payload/game/ui/Section.cc
> +    }
If the page is a nullptr, `onDeinit` is never called in the next loop.

2023-05-29 09:44 UTC, riidefi commented on payload/game/ui/PageId.hh
> +}
While it is true that the repository has many namespaces, I am not sure how I feel about shadowing a typename with a namespace

2023-05-29 09:47 UTC, riidefi commented on payload/game/ui/Section.cc
> +    }
This is irrelevant because `m_activePageCount` will be zero in all cases here, so the values of `m_activePages` will never be inspected. With respect to the other arrays, we rely on the zeroing to avoid a double-free bug

2023-05-29 09:49 UTC, vabold commented on payload/game/ui/Section.cc
> +    }
Oh, sorry, I misunderstood that setting the page to a nullptr would affect `m_pages` and not `m_activePages`. Yes, you're right.

2023-05-29 09:50 UTC, vabold commented on payload/game/ui/Section.cc
> +        if (page == nullptr) {
Should we at least have `auto *&` for transparency about the type?

2023-05-29 10:01 UTC, vabold commented on payload/game/ui/PageId.hh
> +}
Yeah, you're right. Perhaps it is best scoped in `Page` as a static function. I'm hesitant to leave such a specific function in such a generic namespace.

2023-05-29 18:45 UTC, riidefi commented on payload/game/ui/PageId.hh
> +}
I think I like this less, since we should keep the enum functions and static checks as close to the enum as possible for maintainability. Another option could be to add an enum member `PageId::EXT_Count = ...`, but I can't really see much advantage to it.

2023-05-29 18:45 UTC, riidefi commented on payload/game/ui/Section.cc
> +        if (page == nullptr) {
Yes

2023-05-29 18:45 UTC, riidefi commented
I haven't checked with Clang, but if not, we can just conditionally disable that check when we get to it.

2023-05-29 20:39 UTC, stblr commented on payload/game/ui/Section.hh
> +// sizeof(Section) == 0x408 + sizeof(Section::m_pagesEXT) breaks when ExtensionPageCount() is 0
What about `sizeof(Section == 0x408 + sizeof(Page *) * ExtensionPageCount()`?

2023-05-29 20:42 UTC, riidefi commented on payload/game/ui/Section.hh
> +// sizeof(Section) == 0x408 + sizeof(Section::m_pagesEXT) breaks when ExtensionPageCount() is 0
Since the array is not declared `[[no_unique_address]]`, it must be at least 1 byte long when it is *instantiated* in the class, even though it is 0 bytes long itself. The correct expression would be `sizeof(Section) == 0x408 + std::max(sizeof(Section::m_pagesEXT), 1)` which is not great

2023-05-30 00:07 UTC, vabold commented on payload/game/ui/PageId.hh
> +}
> I am not sure how I feel about shadowing a typename with a namespace

Good intuition - it doesn't compile.

Keeping it close to the enum and having a stricter scope does not seem feasible. I'm inclined to prioritize the latter goal. If we cannot keep it close to the enum, we should instead keep it close to its usecase in `Section`.

2023-05-30 00:12 UTC, riidefi commented on payload/game/ui/PageId.hh
> +}
> Another option could be to add an enum member PageId::EXT_Count = ..., but I can't really see much advantage to it.
This would work and maximize both of your goals, but I still am not convinced there is any deficiency with the current approach.

2023-05-30 00:20 UTC, vabold commented on payload/game/ui/PageId.hh
> +}
The deficiency with the current approach is that the function's scope does not match the function's versatility.

Would that member need to be updated manually when a new page is introduced?

2023-05-30 00:29 UTC, riidefi commented on payload/game/ui/PageId.hh
> +}
No, such an approach would not need to be manually updated; an enum value can be any constant expression, even the result of a `constexpr` function.

It's fairly common to immediately place constexpr helpers immediately after an enum in the same scope, e.g. [here](https://github.com/llvm/llvm-project/blob/b936816fb305cc16d2d1cd6d424c08c39a681a32/clang/include/clang/Basic/Specifiers.h#L203) or [here](https://github.com/google/draco/blob/9f856abaafb4b39f1f013763ff061522e0261c6f/src/draco/compression/mesh/mesh_edgebreaker_shared.h#L53).

2023-05-30 04:04 UTC, vabold commented on payload/game/ui/PageId.hh
> +}
Yes, but the enum class is a different scope compared to the enums in these examples. The equivalent of your examples would be `enum PageId` which is accessed as `UI::PAGE_EMPTY` or something similar.

2023-05-30 04:09 UTC, riidefi commented on payload/game/ui/PageId.hh
> +}
No, it's written `Enum_Value` and not `Enum::Value` because `enum class` is a modern C++ feature. In principle, the practice of putting helper methods right below the enum, in the same namespace, is standard practice. If it's good enough for LLVM, it should be good enough for SP.

2023-05-30 19:15 UTC, vabold commented on payload/game/ui/PageId.hh
> +}
@stblr What are your thoughts?

2023-05-30 21:00 UTC, riidefi commented on payload/game/ui/PageId.hh
> +}
Enum class [here](https://github.com/llvm/llvm-project/blob/af8e3861025f3c931cc67ced86d6bd8c939e6fc0/clang/lib/CodeGen/CGValue.h#L130) and [here](https://myanimelist.net/anime/4280/Kara_no_Kyoukai_Movie_4__Garan_no_Dou).

2023-05-30 21:26 UTC, vabold commented on payload/game/ui/PageId.hh
> +}
I'm not deeply familiar with the C++ standard but I do not think "Kara no Kyoukai Movie 4: Garan no Dou" is an enum class.

2023-05-30 21:28 UTC, riidefi commented on payload/game/ui/PageId.hh
> +}
```cpp
/// The source of the alignment of an l-value; an expression of
/// confidence in the alignment actually matching the estimate.
enum class AlignmentSource {
  /// The l-value was an access to a declared entity or something
  /// equivalently strong, like the address of an array allocated by a
  /// language runtime.
  Decl,

  /// The l-value was considered opaque, so the alignment was
  /// determined from a type, but that type was an explicitly-aligned
  /// typedef.
  AttributedType,

  /// The l-value was considered opaque, so the alignment was
  /// determined from a type.
  Type
};

/// Given that the base address has the given alignment source, what's
/// our confidence in the alignment of the field?
static inline AlignmentSource getFieldAlignmentSource() {
  // For now, we don't distinguish fields of opaque pointers from
  // top-level declarations, but maybe we should.
  return AlignmentSource::Decl;
}
```
If it works for LLVM it works for SP. Marking as resolved.

2023-05-30 21:29 UTC, riidefi commented on payload/game/ui/Section.hh
> +// sizeof(Section) == 0x408 + sizeof(Section::m_pagesEXT) breaks when ExtensionPageCount() is 0
Given `sizeof(Section == 0x408 + sizeof(Page *) * ExtensionPageCount())` is not a viable alternative, marking as resolved.

2023-05-30 21:38 UTC, riidefi commented on payload/game/ui/Section.hh
> +// sizeof(Section) == 0x408 + sizeof(Section::m_pagesEXT) breaks when ExtensionPageCount() is 0
This should also be standardized in C++26 https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2023/p2883r0.pdf

2023-05-31 19:53 UTC, stblr commented on payload/game/ui/SectionManager.cc
> +    m_currentSection = new Section;
Looks like the vanilla ctor is not called here, is that intended?

2023-05-31 19:58 UTC, riidefi commented on payload/game/ui/SectionManager.cc
> +    m_currentSection = new Section;
Are you sure? I would expect it to call our GCC default ctor. That is itself an issue, though.

2023-05-31 19:59 UTC, stblr commented on payload/game/ui/SectionManager.cc
> +    m_currentSection = new Section;
Yeah that's what I mean.

2023-05-31 20:15 UTC, riidefi commented on payload/game/ui/SectionManager.cc
> +    m_currentSection = new Section;
Fixed

2023-06-01 02:15 UTC, vabold approved these changes

2023-06-01 21:13 UTC, stblr approved these changes

2023-06-01 21:14 UTC, merged