Ensure that battle stages do not appear on the leaderboards
stblr/mkw-sp pull request #804
Opened 2023-06-01 14:05 UTC by MikeIsAStar

2023-06-01 14:06 UTC, vabold approved these changes

2023-06-03 18:45 UTC, stblr requested changes
This breaks thumbnail preloading.

The `race` part of the filter is already overridden if we are in the `Rankings` section, we should simply do the same for the `battle` part.

2023-06-04 03:24 UTC, vabold commented
> The `race` part of the filter is already overridden if we are in the `Rankings` section, we should simply do the same for the `battle` part.

Instead of incorporating multiple potential usecases over time, we instead solve the problem now by extending the `filter` helper function to allow filters as arguments.

2023-06-04 03:30 UTC, MikeIsAStar commented
> This breaks thumbnail preloading.
> 
> The `race` part of the filter is already overridden if we are in the `Rankings` section, we should simply do the same for the `battle` part.

Resolved by commit [1f5cc52](https://github.com/stblr/mkw-sp/pull/804/commits/1f5cc52658c8928ecb22bf5d5ac676f085043ac1).

2023-06-06 20:37 UTC, stblr approved these changes

2023-06-06 20:38 UTC, merged