Use SceneId enum
stblr/mkw-sp pull request #813
Opened 2023-06-02 22:33 UTC by GnomedDev

Renames `System::RKSceneId` to `EGG::SceneId` and uses it more. This also replaces a couple of pointer arguments with references for safety reasons, but that could be easily reverted if disliked.

2023-06-02 23:44 UTC, vabold requested changes

2023-06-02 23:44 UTC, vabold commented on payload/egg/core/eggSceneManager.cc
> +void SceneManager::createScene(EGG::SceneId sceneId, Scene &parent) {
```suggestion
void SceneManager::createScene(EGG::SceneId sceneId, Scene *parent) {
```
The function explicitly checks if `parent` is a nullptr.

2023-06-02 23:44 UTC, vabold commented on payload/egg/core/eggScene.hh
> +enum class SceneId : u32 {
```suggestion
enum class SceneId {
```

2023-06-02 23:44 UTC, vabold commented on payload/egg/core/eggSceneManager.cc
> +        createScene(sceneID, *parent);
```suggestion
        auto *parent = m_currScene->getParent();
        auto sceneID = m_currScene->id();
        destroyScene(*m_currScene);
        createScene(sceneID, parent);
```

2023-06-02 23:44 UTC, vabold commented on payload/egg/core/eggSceneManager.hh
> +    void REPLACE createScene(EGG::SceneId sceneId, Scene &parent);
```suggestion
    void REPLACED(createScene)(EGG::SceneId sceneId, Scene *parent);
    void REPLACE createScene(EGG::SceneId sceneId, Scene *parent);
```

2023-06-02 23:45 UTC, vabold commented
It's likely that we do not want to move the game-specific scene IDs out of `host_system` and into `EGG` as the library is not game-dependent.

2023-06-07 03:21 UTC, vabold requested changes

2023-06-07 03:21 UTC, vabold commented on payload/game/ui/Section.hh
>  #include <nw4r/lyt/lyt_drawInfo.hh>
```suggestion
#include "game/host_system/Scene.hh"

#include <nw4r/lyt/lyt_drawInfo.hh>
```

2023-06-07 03:21 UTC, vabold commented
Nice work!

2023-06-12 22:40 UTC, GnomedDev commented on payload/game/ui/Section.hh
>  #include <nw4r/lyt/lyt_drawInfo.hh>
Done

2023-06-12 23:34 UTC, vabold approved these changes

2023-06-14 20:34 UTC, stblr approved these changes

2023-06-14 20:34 UTC, merged